### ISSUE TITLE
Missing API V3 data

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-api#100]
- [x] Words are missing `pageNumber`
Needed for doing reading mode.

- [ ] Support returning images instead of words, if the text type is sent.
This will be used for PDF.

- [x] Verses are not returning translations when requested
`http://staging.quran.com:3000/api/v3/chapters/1/verses?recitation=1&translations=%5B21%5D&language=en` results in no translations

- [x] Translations options returning nothing

**Comment by mmahalwy** [comment]
Closing. We can tackle images later.

**Comment by naveed-ahmad** [comment]
@mmahalwy 

* Words do have pageNumber, sample response: 
```json
{"id":1,"position":1,"text_madani":"بِسْمِ","text_indopak":null,"text_simple":"بسم","verse_key":"1:1","class_name":"p1","line_number":2,"page_number":1,"code":"&#xfb51;","char_type":"word","audio":null,"translation":{"language_name":"english","text":"In (the) name"},"transliteration":{"language_name":"english","text":"bis'mi"}}
```

* Support of images https://github.com/quran/quran.com-api/pull/101
* Missing Translation, problem is with parameters. It should be `translations[]=21` and if you need multiple translation url will be like `translations[]=21&translations[]=22`

**Comment by mmahalwy** [comment]
Yep, I added it :)

**Comment by mmahalwy** [comment]
Okay, makes sense. There are two ways to do arrays in url. We used the other way but makes sense about this way!

**Comment by mmahalwy** [comment]
I'll remove the `eval`

**Comment by naveed-ahmad** [comment]
api/v3/chapters/1/verses?translations=**Verse.delete_all** 

And we'll lose verses data because of evil eval :)

**Comment by mmahalwy** [comment]
Good point!
