### ISSUE TITLE
Specs 

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-api#105]
Previous specs are irrelevant due to huge changes in schema.

**Comment by mmahalwy** [comment]
+1 on this.

I think the first testing that should be added is rubocop. You and I have different styling of code, and I use rubocop to lint. Travis should lint via rubocop please :)

**Comment by ahmadhasankhan** [comment]
Is someone working on this ? If not then i would like to take it up.

**Comment by mmahalwy** [comment]
please please! No one is currently working on this since we had a huge v3 rewrite, take it away @ahmadhasankhan

**Comment by korabh** [comment]
Hey @ahmadhasankhan, Let me know if I can help.

**Comment by ahmadhasankhan** [comment]
> Hey @ahmadhasankhan, Let me know if I can help.

@korabh Yeah sure, lets start together.

**Comment by mmahalwy** [comment]
I am adding graphql too! That might be a great candidate for specs :)
