### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-api#122]
A call such as:
```
http://localhost:3000/api/v3/chapters/2/verses?recitation=1&translations=%5B21%5D&language=en&text_type=words&page=4
```

Has these bottlenecks:

```
 [Debug]      (211.4ms)  SELECT "translations"."language_id" FROM "translations" WHERE "translations"."resource_type" = $1  [["resource_type", "Verse"]] (pid:65170)
```
211ms is too long.

Results to:
```
 [Info]   Completed 200 OK in 9385ms (Views: 8052.1ms | ActiveRecord: 791.5ms)
```

**Comment by ahmedre** [comment]
some things stand out to me:

1. let's not send null valued keys - i.e.

```
                    "text_indopak": null,
                    "text_madani": null,
                    "text_simple": null,
                    "translation": null,
                    "transliteration": null,
```

it's a waste of bytes to send these - if it's not there, it's null.

2. can we offload audio to a separate request when audio is played the first time? seems like a waste in many cases where either audio is not played or people change the qari before playing.

**Comment by mmahalwy** [comment]
I agree with @ahmedre

**Comment by ahmedre** [comment]
let's make sure indices are properly setup with the new schema also.

**Comment by mmahalwy** [comment]
Okay, got it down to 

```
 [Info]   Completed 200 OK in 928ms (Views: 849.7ms | ActiveRecord: 71.2ms)
```

**Comment by mmahalwy** [comment]
We can close this now. we have improved alot
