### ISSUE TITLE
Get Verse

### ISSUE THREAD

**Issue by AncientDeer** [quran/quran.com-api#134]
It's not working? Gives error 404 Not Found. 
http://staging.quran.com:3000/api/v3/verses/{id}
What do i put for {id}?

**Comment by naveed-ahmad** [comment]
There is no endpoint to get individual verse, but you can get details of single verse by controlling values of `page`, `limit` & `offset` params  

1:1 => http://staging.quran.com:3000/api/v3/chapters/1/verses?page=1&limit=1
1:2 => http://staging.quran.com:3000/api/v3/chapters/1/verses?page=1&limit=1&offset=1
1:7 => 1:1 => http://staging.quran.com:3000/api/v3/chapters/1/verses?page=1&limit=1&offset=6

Please refer to documentation for more detail: https://quran.api-docs.io/v3/verses
