### ISSUE TITLE
Word translation issue

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-api#139]
quran.com/9/51

Last two words has same translation: 
 فَلْيَتَوَكَّلِ => [so] let the believers put (their) trust
 الْمُؤْمِنُونَ => [so] let the believers put (their) trust

Correct translation would be( I believe ):
 فَلْيَتَوَكَّلِ => let put (their) trust
 الْمُؤْمِنُونَ => The believers

Ref: http://corpus.quran.com/wordmorphology.jsp?location=(3:122:11)

**Comment by azulkipli** [comment]
and I think translation of وَعَلَى => "and on" on this ayah should be "and upon"

**Comment by naveed-ahmad** [comment]
Confirmed from Dr.Mustafa 


فَلْيَتَوَكَّلِ => let put (their) trust
الْمُؤْمِنُونَ => The believers

**Comment by naveed-ahmad** [comment]
Fixed.
