### ISSUE TITLE
Unsure of how the Get Verse API call works.

### ISSUE THREAD

**Issue by Asad3ainJalout** [quran/quran.com-api#150]
Assallamu Alaikum,

I am trying to get a specific verse. I am unsure of how to call it. According to this page https://quran.api-docs.io/v3/verses/get-verse you need to give it an id. However, no variation of numbers seems to be getting me the verse. I have tried "1:1","1,1", "1/1", "1" etc. etc. to no avail.

Thank you for your help.

**Comment by naveed-ahmad** [comment]
Duplicated: https://github.com/quran/quran.com-api/issues/134

thanks for reporting issue in docs :)
