### ISSUE TITLE
Word Translation Issue

### ISSUE THREAD

**Issue by azizur** [quran/quran.com-api#162]
See the image below.
![screen shot 2017-09-15 at 08 14 13](https://user-images.githubusercontent.com/114551/30471189-9c33f428-99ef-11e7-9405-9275ea8ac361.png)

**Comment by naveed-ahmad** [comment]
correct translation: before it

thanks to Dr.Mustafa for helping.

**Comment by mmahalwy** [comment]
How are these different? https://github.com/quran/quran.com-api/issues/139

**Comment by naveed-ahmad** [comment]
Both are translation issues, but #139 is for another ayah.

**Comment by naveed-ahmad** [comment]
@azizur fixed on staging, can you please confirm its fixed?
