### ISSUE TITLE
How can I access specific juz ?

### ISSUE THREAD

**Issue by tweetzal** [quran/quran.com-api#164]
ASA,

How can I access specific juz ?

What is api call ref ?

I am making a web app for Khatam al Quran

Mo

**Comment by naveed-ahmad** [comment]
You mean getting ayah for specific Juz? Not possible currently, but there is a workaround.

- Get all juzs: https://quran.api-docs.io/v3/juz/get-all-juzs
- `verse_mapping` key will give you list of surah, and ayahs for each juz. Then you can use versus endpoint to get those ayah

**Comment by tweetzal** [comment]
JazaakAllah
