### ISSUE TITLE
Another text issue

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-api#177]
I know its same word just different way of writing but need to follow standards. 

https://quran.com/13/6
http://tanzil.net/#13:6

وَيَسْتَعْجِلُونَكَ بِالسَّيِّئَةِ قَبْلَ الْحَسَنَةِ وَقَدْ خَلَتْ مِن قَبْلِهِمُ الْمَثُلَاتُ ۗ وَإِنَّ رَبَّكَ لَذُو مَغْفِرَةٍ لِّلنَّاسِ عَلَىٰ ظُلْمِهِمْ ۖ وَإِنَّ رَبَّكَ لَشَدِيدُ الْعِقَابِ - 13:6

الْمَثُلَاتُ OR المَثُلـٰتُ ?

**Comment by ahmedre** [comment]
المَثُلـٰتُ is how you'd find it in the mus7af - in uthmani script.
الْمَثُلَاتُ is how you'd find it in the tafseer or in normal writing today - in imlaei script (modern written Arabic script).

both are right, it just depends on which we want to go with - we should be consistent irrespective.

**Comment by ahmedre** [comment]
cc @hammady for thoughts

**Comment by naveed-ahmad** [comment]
فَاصْبِرْ كَمَا صَبَرَ أُولُو الْعَزْمِ مِنَ الرُّسُلِ وَلَا تَسْتَعْجِل لَّهُمْ ۚ كَأَنَّهُمْ يَوْمَ يَرَوْنَ مَا يُوعَدُونَ لَمْ يَلْبَثُوا إِلَّا سَاعَةً مِّن نَّهَارٍ ۚ بَلَاغٌ ۚ فَهَلْ يُهْلَكُ إِلَّا الْقَوْمُ الْفَاسِقُونَ - 46:35

بَلَاغٌ OR بَلـٰغٌ

**Comment by naveed-ahmad** [comment]
وَاللَّائِي يَئِسْنَ مِنَ الْمَحِيضِ مِن نِّسَائِكُمْ إِنِ ارْتَبْتُمْ فَعِدَّتُهُنَّ ثَلَاثَةُ أَشْهُرٍ وَاللَّائِي لَمْ يَحِضْنَ ۚ وَأُولَاتُ الْأَحْمَالِ أَجَلُهُنَّ أَن يَضَعْنَ حَمْلَهُنَّ ۚ وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مِنْ أَمْرِهِ يُسْرًا - 65:4

وَاللَّائِي OR وَالّـٰـٔى

**Comment by hammady** [comment]
One should stick to the Uthmani script. It is a common debate among scholars but sticking to it is the safest. Please see this [fatwa](http://fatwa.islamweb.net/fatwa/index.php?page=showfatwa&Option=FatwaId&Id=146011).

**Comment by hammady** [comment]
Please also note that the Uthmani script takes into consideration the variation in pronunciation for the different rewayat (more evident if we also remove the dots).

**Comment by udotag** [comment]
![ayah-reference](https://user-images.githubusercontent.com/44333106/47279357-db692f00-d5e9-11e8-9bbf-f949dc21eda0.png)

![img_0809](https://user-images.githubusercontent.com/44333106/47279356-d73d1180-d5e9-11e8-9753-243126c80b6a.png)

اسلام عليكم ورحمة الله 

there is, as I see and understand it, a discrepancy in the pictures above. 
the website is not conforming to the script of سيدنا عثمان رضى الله عنه in the above instance, as well.

**Comment by udotag** [comment]
another example : 

https://quran.com/62/11
http://tanzil.net/#62:9

**Comment by udotag** [comment]
is there a central place to log these fixes?

**Comment by naveed-ahmad** [comment]
Added both Uthmani and Imlaei text in api. Now we have Uthmai, Uthmani simple, Imlaei, and Imlaei simple text for ayahs and words. Still need to update the api.

**Comment by naveed-ahmad** [comment]
@udotag please open new issue and list down the problem you found. This was actually Uthmani vs Imlaei problem.
