### ISSUE TITLE
API Resource: Verse Word

### ISSUE THREAD

**Issue by wbashir** [quran/quran.com-api#181]
![image](https://user-images.githubusercontent.com/825838/35744154-369db9e4-0805-11e8-88fe-bd297b319a1a.png)

Salam, Is the verse word exposed in the QURAN API by chance?

**Comment by naveed-ahmad** [comment]
Wa Alaikum o Salam,  this is glyph code that we're using to render the mushaf. One day inshAllah we'll replace these code with actual text.
