### ISSUE TITLE
Add Rack::Attack

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-api#183]
https://github.com/kickstarter/rack-attack

**Comment by hammady** [comment]
Moving forward with microservices, swarm, ... etc, it is better IMHO to handle this in the nginx layer. The benefit will be protecting frontend, api, fonts, ... and any service we add in the future. Moreover, the vision is to have a single cluster with 1 nginx that handles all our apps like legacy, downloads, android, ... You don't want to worry about protection in every single service.

**Comment by mmahalwy** [comment]
I agree! Good call
