### ISSUE TITLE
Access root letters for individual words

### ISSUE THREAD

**Issue by asavera** [quran/quran.com-api#185]
Salaam, Sorry for creating the Issue item, I didn't know how to contact otherwise. 

I'm using this API for my project and I'm able to access the words per verse but I couldn't find the root letters. Can you guide me how to access them if that feature is already supported by this API.

Jazak Allah Khair,

**Comment by naveed-ahmad** [comment]
Word roots, stem, lemma and couple other data points are available through REST api yet, you can  this data via graphql endpoint but this endpoint isn't stable yet. 

http://staging.quran.com:3000/graphiql

Sample query for words with roots
```
query{
  verses(chapterId: 1) {
    id
    words{
      id
      textMadani
      roots {
        id
        value
      }
    }
  }
}
```

**Comment by asavera** [comment]
thanks for a quick response. would appreciate help with one more thing.

i'm trying to access individual verse e.g. at http://staging.quran.com:3000/api/v3/verses/4 but getting error. can you please guide me to the correct endpoint to fetch one verse. jazak Allah Khair.

**Comment by naveed-ahmad** [comment]
Salam, you can get verse using `/chapter/1/verses` endpoint, then use `page`, `offset` and `limit` params to fetch specific verse. 
 
We need to fix the docs, there is no way to fetch verse directly( e.g verses/id).

**Comment by asavera** [comment]
thanks for a prompt reply. i'm not sure I understand how to use the page, offset and limit params u mentioned, i didn't find details in the documentation. can you give please give an eg. how I would fetch verse 187 from chapter 2 .

jazak Allah khair

**Comment by asavera** [comment]
jazak Allah khair brother for the clarification and your time.

**Comment by asavera** [comment]
sorry to bother you again. in the verse list returned, can u tell what "code" and "code_v3" represent in the response.
