### ISSUE TITLE
Request for DB access or Production API usage

### ISSUE THREAD

**Issue by fikriauliya** [quran/quran.com-api#188]
Assalamualaykum,

I would like to create an App focusing on Quran memoization. It would be open source weekend-project and for non-commercial. I am not Android/iOS developer, so probably I would try Flutter or RN.

I have read some old PRs related to DB access. So I wonder which one is more preferred:

1) The app would use the production API directly https://quran.com/api/graphql
+: The server cost is not on me (but do you mind?)
-: If there is non-backward-compatible change on the same endpoint, the app would crash

2) I request for DB access and I would host it directly on my server

3) I clone the API to Firebase (inspecting the request-response and put it on Firebase)

If you prefer replying on email, mine is: pahlevi.fikri.auliya@gmail.com
Or please let me know which email address I could send to :).

**Comment by naveed-ahmad** [comment]
WaAlakim o Salam,

I don't think you'll want to manage the database( couple of GBs btw ) for a weekend project. You can use Quran.com api as long as app doesn't have advertisements. 

Documentation: https://quran.api-docs.io/v3/getting-started/introduction
Sample api calls:
https://staging.quran.com/api/api/v3/chapters
https://staging.quran.com/api/api/v3/chapters/1
https://staging.quran.com/api/api/v3/chapters/1/verses

Graphql endpoint: http://staging.quran.com:3000/graphiql

The current version of API is v3, new major releases will have different URL, we'll try to keep supporting previous versions inshAllah. Don't worry about backward compatibility :) 

Develop something great, good luck!

**Comment by fikriauliya** [comment]
Great! 
I will share the link to the Github repo here once it is done :)

**Comment by GibreelAbdullah** [comment]
http://staging.quran.com:3000/graphiql doesn't work.
