### ISSUE TITLE
hard hit count limit for the api end-points?

### ISSUE THREAD

**Issue by adamchenwei** [quran/quran.com-api#190]
Asalam Alaykum,
May Allah reward you all for this wonderful project. ameen.

I read a thread about access to db, and saw we can have access to it, so
I wonder if there is any hard hit count limit if I build a front end application that may frequently hitting the api? is the api I am hitting need to host myself and only having access to db as a read only user or its your server that grant access to the api with db data? I do not have one in mind yet, but would like to know there is already an backend like yours there to utilize, so I can work with it. It would good to know how frequent consider as excessive, in shaa Allah.

**Comment by naveed-ahmad** [comment]
WaAlakim o salam brother. 

You can use api, there is no limit for now. But if your application became super famous one day inshAllah, then you should consider deploying this to your own server. 

Here is api docs: https://quran.api-docs.io/v3
