### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-api#194]
- Use https://github.com/malomalo/turbostreamer for streaming json ( or simply ise to_json, benchmark the performance) 
- Pagy for pagination https://github.com/quran/quran.com-api/issues/192
- `include_in_response` params for adding related content to response(e.g verses?include_in_response=translations|words)
- Move media to separate api call 

And finally, finish graphql client

**Comment by mmahalwy** [comment]
i can work on the graphql part

**Comment by OrkhanAlikhanov** [comment]
+1 GraphQL would make fetching and data handling a lot easier
