### ISSUE TITLE
Getting error for tafsir

### ISSUE THREAD

**Issue by sarfraznawaz2005** [quran/quran.com-api#200]
AOA,

I am getting 500 server error when trying to get tafsir:

http://staging.quran.com:3000/api/v3/chapters/1/verses/1/tafsirs?tafsirs=ur_ibn_kathir

https://quran.api-docs.io/v3/tafsirs/get-specific-tafsir-of-a-verse

Thanks

**Comment by naveed-ahmad** [comment]
WaAlakim o Salam.
 
Here is production url: http://www.quran.com:3000/api/v3/chapters/1/verses/1/tafsirs?tafsirs=ur_ibn_kathir

Staging is meant to be break while we're testing something. Isn't it :)

**Comment by sarfraznawaz2005** [comment]
Thanks I know but it does that end point does not yield expected result. You see I had entered tafsir parameter to be urdu but results show more than one entry instead of one plus and no entry is in urdu, all are in arabic. So something is still wrong with the result. On staging, it used to show right results with urdu tafseer and one entry.

Thanks

**Comment by sarfraznawaz2005** [comment]
So issue still persists.

**Comment by sarfraznawaz2005** [comment]
Issue is closed while it is not resolved. Any update on this please ?

**Comment by naveed-ahmad** [comment]
@sarfraznawaz2005 Sorry I missed this earlier, you're getting all tafisrs because you're using wrong slug in query string. We never had `Ibn e khatir` in Urdu.  API is working fine, try following url and you'll get only one tafsir. 

http://www.quran.com:3000/api/v3/chapters/1/verses/1/tafsirs?tafsirs=ar_tanweer

We'll add Urdu tafsir soon inshAllah.

**Comment by sarfraznawaz2005** [comment]
Thansk, urdu ibn-khatir tafseer used to come on staging url before, this can be verified by going to this endpoint http://staging.quran.com:3000/api/v3/options/tafsirs but unfortunately none staging endpoints works anymore due to some server internal error.

Waiting for urdu tafseer to be implemented on production soon.

JazakaAllah
