### ISSUE TITLE
rubocop-rails is renamed to rubocop-rails_config.

### ISSUE THREAD

**Issue by udotag** [quran/quran.com-api#202]
got this message at the end of bundle install
consider changing Gemfile in master
shukran.

Post-install message from rubocop-rails:
rubocop-rails is renamed to rubocop-rails_config. To migrate to new gem, install rubocop-rails_config instead of rubocop-rails.

gem "rubocop-rails_config"

Then, run update command.

$ bundle exec rails generate rubocop_rails_config:update

**Comment by naveed-ahmad** [comment]
thanks for reporting @udotag updated.
