### ISSUE TITLE
DB Access local 

### ISSUE THREAD

**Issue by wbashir** [quran/quran.com-api#203]
Salaam,

How to get access to the database.sql file? Working to better understand the source Inshallah?

**Comment by wbashir** [comment]
Based on the long conversation's here https://github.com/quran/quran.com-api/issues/44. I don't think the DB is going to be handed out. I am working some deep learning models and would like to get at minimum just the SCHEMA of your DB and not the data. I will use the API when i need the data itself @sharabash @ahmedre

**Comment by naveed-ahmad** [comment]
@wbashir can you work with Ruby? If so here is the schema: https://github.com/quran/quran.com-api/blob/master/db/schema.rb

Can you email me naveedahmada036@gmail.com with more detail about your project and which data you need and maybe I can try exporting subset of data for you.
