### ISSUE TITLE
Step By Step Guide To Setting Up A Local API

### ISSUE THREAD

**Issue by Skillz4Killz** [quran/quran.com-api#208]
Asalamoalaikum Wa Rahmatullahi Wa Barakatuhu

The process to get a local API running is a bit confusing. After cloning the repo, and attempting to install it threw an error that my Ruby was not the right version so I used rvm to downgrade to 2.3.3 as suggested by the error. 

After downgrading to 2.3.3 by following the errors instructions:

```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
        from /usr/local/bin/bundle:22:in `<main>'
```

Then I tried to go and follow the PGSQL method and installed the app and then did the gem install and it threw an error.
```
This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

// Looking into the error file
conftest.c:3:10: fatal error: 'libpq-fe.h' file not found
#include <libpq-fe.h>
         ^~~~~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libpq-fe.h>
/* end */
```

I am hoping for a better possibly more updated guide that can be followed to get the API working locally.

In case computer specs are needed:
![image](https://user-images.githubusercontent.com/23035000/49404212-cde0b200-f71c-11e8-83d2-f63fbc0f9cd8.png)

**Comment by naveed-ahmad** [comment]
This is PostgreSQL issue. Please search on stackoverflow for solution.
