### ISSUE TITLE
Feature Request: Urdu Tafsir

### ISSUE THREAD

**Issue by sarfraznawaz2005** [quran/quran.com-api#209]
AOA,

Previously, Urdu Tafsir used to come fine on following exact staging URL:

http://staging.quran.com:3000/api/v3/chapters/1/verses/1/tafsirs?tafsirs=ur_ibn_kathir

but now staging URL does not seem to work.

I understand staging URL is for development only but my point is that Urdu Tafsir was functional on that URL.

Can you please implement Urdu Tafsir also on production URL too.

Thanks

**Comment by sarfraznawaz2005** [comment]
Can you please at least guide me maybe I can help you guys to fix this issue if you don't plan to fix this ? Thanks

**Comment by naveed-ahmad** [comment]
Tafsir data is added now

v3: https://api.quran.com/api/v3/chapters/1/verses/1/tafsirs/160
v4: https://api.quran.com/api/v4/quran/tafsirs/160?chapter_number=1

**Comment by sarfraznawaz2005** [comment]
Great. JazakAllah
