### ISSUE TITLE
PHP cURL: "Failed to connect to staging.quran.com port 3000: Connection refused"

### ISSUE THREAD

**Issue by iHassan** [quran/quran.com-api#213]
Assalam-o-alaikum,

When I try any of the following URL on localhost, they work fine

http://www.quran.com:3000/api/v3/chapters
http://staging.quran.com:3000/api/v3/chapters

but when I try to call these URLs from any of my hosting sites, they give me this error on cURL:

**"Failed to connect to www.quran.com port 3000: Connection refused"**

Few things to note:
 I am on shared hosting.
 I have tried 3 different servers (on different shared hosting servers)

Any help would really be highly appreciated. Thanks!

**Comment by iHassan** [comment]
@sarfraznawaz2005 is there anything you can help me with? I admire your work from a long time :)

**Comment by sarfraznawaz2005** [comment]
@iHassan There could be quit some reasons about that issue. I suggest you to checkout this thread https://stackoverflow.com/questions/43898858/curl-connection-refused-from-php-but-works-from-command-line

**Comment by naveed-ahmad** [comment]
Production api url should be: https://www.quran.com/api/api/v3/chapters

➜  ~ curl https://www.quran.com/api/api/v3/chapters
{"chapters":[{"id":1,"chapter_number":1,"bismillah_pre 
....

**Comment by kanta-mir** [comment]
mya be it should be updated -> http://api.quran.com/api/v3/chapters
