### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by arnauduanra** [quran/quran.com-api#215]
A salam alaykoum, 

I am accessing the API data through http://staging.quran.com:3000/api/v3/chapters/2/verses?recitation=1&translations=21&language=ar&limit=50&text_type=words. 

The verse number 6 writing: 

"...إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُم"

is different from the website : 

![Screenshot 2019-03-28 at 14 54 44](https://user-images.githubusercontent.com/27618471/55136504-88cc0a00-5169-11e9-8b82-8dcc8ecd79e9.png)

In the API, the first hamza of "أَأَنذَرْتَهُم is written on a alif. 
In the website, it's written on the line.

**Comment by naveed-ahmad** [comment]
https://github.com/quran/quran.com-api/issues/177

This is actually uthmani vs imlaei script. Same text written using two different styles. 

On quran.com fonts we're using are written using uthmani script but actual text is in imlaei script. I'm in process on moving text to uthmani script. Ayah text is easy to replace, but word by word text will need lots of work..

**Comment by ahmedre** [comment]
+1 for switching to Uthmani script.

**Comment by naveed-ahmad** [comment]
This took a while but fixed now alhumudAllah.
