### ISSUE TITLE
Question regarding transliteration 

### ISSUE THREAD

**Issue by fizcoder** [quran/quran.com-api#217]
When I run the API request for Verses for example:

http://staging.quran.com:3000/api/v3/chapters/1/verses?recitation=1&translations=21&language=en&text_type=words

The translation and transliteration return the same result. Shouldn't transliteration be the Arabic written using the Latin/Roman alphabet?

**Comment by naveed-ahmad** [comment]
We've disabled the word by word transliteration. Copyright issues :(

**Comment by fizcoder** [comment]
Oh :-S 

Thanks for letting me know.
