### ISSUE TITLE
Accessing all verses

### ISSUE THREAD

**Issue by fizcoder** [quran/quran.com-api#218]
I am attempting to retrieve verses for example:

http://staging.quran.com:3000/api/v3/chapters/87/verses

It returns the first 10 verses. But when I added a 'page' query string, for example: 

http://staging.quran.com:3000/api/v3/chapters/87/verses?recitation=1&translations=21&language=en&page=591&text_type=words

or 

http://staging.quran.com:3000/api/v3/chapters/87/verses?recitation=1&translations=21&language=en&page=592&text_type=words

No verses are returned. Please advice. Thanks.

**Comment by fizcoder** [comment]
Also, when I attempt to use the verse API for example:

http://staging.quran.com:3000/api/v3/verses/1

I get the following message:

> The page you were looking for doesn't exist.
> You may have mistyped the address or the page may have moved.
> If you are the application owner check the logs for more information.

**Comment by sabeurthabti** [comment]
https://quran.api-docs.io/v3/chapters/list-chapters
might be helpful, until others with better knowledge help you.

**Comment by fizcoder** [comment]
Thanks for your response. But I'm not sure how that helps with my issue.

**Comment by naveed-ahmad** [comment]
Surah 87 has only 19 ayah, that means only two pages. `page=591` is query string wont return any ayah. 

Api also has `limit` query string that you can use to increase the number of ayah in response. I think maximum value for `limit` is 50. 

Try following URL to load all ayahs. 

http://staging.quran.com:3000/api/v3/chapters/87/verses?recitation=1&translations=21&language=en&limit=50&text_type=words

**Comment by fizcoder** [comment]
Many thanks! That worked!
