### ISSUE TITLE
The character used for the sukun is not correct. 

### ISSUE THREAD

**Issue by arnaud-zad** [quran/quran.com-api#219]
As salam alaykoum,

I am fetching data from http://staging.quran.com:3000/api/v3/chapters/2/verses?translations=21. 

I am using Uthmani font (available here: https://fonts.qurancomplex.gov.sa/wp02/%D8%AD%D9%81%D8%B5#05). 

Here is the result for the 5th ayah of Al Baqarah: 

![Screenshot 2019-05-22 at 10 12 43](https://user-images.githubusercontent.com/27618471/58142564-2e878b00-7c7a-11e9-9cc8-ab389ec60de3.png)

The character above the waw doesn't seem to be a sukun. When I change to a sukun manually, it's displayed correctly: 

![Screenshot 2019-05-22 at 10 13 24](https://user-images.githubusercontent.com/27618471/58142600-5c6ccf80-7c7a-11e9-9ed8-99f281854c00.png)

**Comment by naveed-ahmad** [comment]
This script is compatible with me_quran font, here is the test.

https://naveed-ahmad.github.io/test-arabic-fonts/#fontSize=30&fontBold=false&text=%D8%A3%D9%8F%D9%88%DB%9F%D9%84%D9%8E%D9%B0%D9%93%D8%A6%D9%90%D9%83%D9%8E%20%D8%B9%D9%8E%D9%84%D9%8E%D9%89%D9%B0

**Comment by arnaud-zad** [comment]
It's not only being compatible with a font, it's also about the correctness of the text. 

Check at the character I told you. It should be a sukun but it's not.

**Comment by naveed-ahmad** [comment]
We're using Uthmani script from tanzil, and this script is only compatible with me_quran font

http://tanzil.net/#2:5

![Al Baqara  2 5    Tanzil Quran Navigator](https://user-images.githubusercontent.com/701567/58203750-4c91d180-7cf4-11e9-9f3d-2a9b0c4c64db.png)

It is sakoon but they're using different codepoint which maybe isn't compatible with font you're using? 

![Arabic fonts testing](https://user-images.githubusercontent.com/701567/58203880-8f53a980-7cf4-11e9-8bff-7dcbfa69a304.png)

**Comment by arnaud-zad** [comment]
Okay you're right there are different codepoint for the sukun. Jazak Allah khayran. 

Just for information I tried with https://naveed-ahmad.github.io/test-arabic-fonts/#fontSize=30&fontBold=false&text=%D9%82%D9%8E%D8%A7%D9%84%D9%8F%D9%88%D8%A7%D9%92%20%D9%8A%D9%8E%D9%B0%D9%93%D8%A3%D9%8E%D8%A8%D9%8E%D8%A7%D9%86%D9%8E%D8%A7%20%D9%85%D9%8E%D8%A7%20%D9%84%D9%8E%D9%83%D9%8E%20%D9%84%D9%8E%D8%A7%20%D8%AA%D9%8E%D8%A3%D9%92%D9%85%D9%8E%DB%AB%D9%86%D9%91%D9%8E%D8%A7%20%D8%B9%D9%8E%D9%84%D9%8E%D9%89%D9%B0%20%D9%8A%D9%8F%D9%88%D8%B3%D9%8F%D9%81%D9%8E%20%D9%88%D9%8E%D8%A5%D9%90%D9%86%D9%91%D9%8E%D8%A7%20%D9%84%D9%8E%D9%87%D9%8F%DB%A5%20%D9%84%D9%8E%D9%86%D9%8E%D9%B0%D8%B5%D9%90%D8%AD%D9%8F%D9%88%D9%86%D9%8E. 

Only Amiri and QuranTaha (for madani) are displaying correctly the text. me_quran is displaying the mad on the ya too close to the alif. 

So actually very few options are available for the font.

**Comment by atefBB** [comment]
It's not a sokoon but it's for an ignored letter in the word `أولئك`!
