### ISSUE TITLE
Slack Sign up link not working

### ISSUE THREAD

**Issue by FawazFarid** [quran/quran.com-api#221]
The Slack Sign up link provided i.e. https://quranslack.herokuapp.com does not work. Getting the following Heroku error message.

<img width="940" alt="Screen Shot 2019-07-30 at 3 24 20 PM" src="https://user-images.githubusercontent.com/17722450/62129756-28e49c00-b2e0-11e9-8c30-fde7b4ecfa28.png">

**Comment by naveed-ahmad** [comment]
Yeah, we stopped using it. Post your email here and ill invite you iA

**Comment by FawazFarid** [comment]
@naveed-ahmad sure, my email is: fawwazally@gmail.com
