### ISSUE TITLE
How can I get the quran database

### ISSUE THREAD

**Issue by mobileexpert1** [quran/quran.com-api#224]
Hello Team,Can you please let me know I can get the Quran database access. I want to create an app same like quran. So i need the quran database. Can you please provide me the database access. 

Thank You

**Comment by naveed-ahmad** [comment]
Sorry @mobileexpert1 we can't share the db. There are many issues with sharing the complete dump. 

- We don't own the translations 
- We're not allowed to share the wbw audio 
- Translation keep changing, typos, new version and what not. And there is no way to share the the updated db

Ill suggest you to use our api for your app. You can access everything via api, and you'll updated content whenever something changed.

**Comment by azzamsa** [comment]
@naveed-ahmad Thank you for quran.com

I am curious about:
- where does the quran.com team get the Quran text?
- if you don't own the translation and wbw audio, then who is the owner, what is the license?

I don't find these answer in https://quran.com/about#credits

related:
- https://github.com/quran/quran.com-api/issues/188
- https://github.com/quran/quran.com-api/issues/44#issuecomment-220098919

Love to read an article on how quran.com teams build the Quran source (text, audio, translation)

thank you.

**Comment by naveed-ahmad** [comment]
@azzamsa Sorry saw your questions today, two years later :( 

> where does the quran.com team get the Quran text
- Uthmani script( compatible with meQuran font) was taken from Zerk project( discontinued long ago but you can find it on archive) and Tanzil 
- New Uthmani script was taken from https://qurancomplex.gov.sa/ and it's compatiable with their Hafs font, current version is v.17
- Indopak was taken for PDMS

> wbw auduio
taken from recitequran.com, Sheikh Yusuf estes is the owner of this site 

> translations 
from many sources, tanzil, quranenc, lot of translations were shared with us by authors.

**Comment by azzamsa** [comment]
It's okay :).

Thanks a lot for the reply.
