### ISSUE TITLE
audio resource and search issue 

### ISSUE THREAD

**Issue by minhpdn** [quran/quran.com-api#234]
Hi, 
I'm developing the app using your API. I just know this way to contact you so I created this issue. Sorry for this. I have a question about the url of audio like

![image](https://user-images.githubusercontent.com/13447967/75238143-19d0b880-57f3-11ea-8221-22fed5b6bf3a.png)
What is the full url of it ?  so I can download the resource .
And the second is about the search. I'm using this 
http://staging.quran.com:3000/api/v3/search?q=among&size=20&page=0&language=en

but it's alway return error code 500. Can you explain the right way to use this API.
Thanks,
MInh

**Comment by naveed-ahmad** [comment]
CDN host for audio is `https://audio.qurancdn.com/` and search is down on staging. Upgrading ES stack, this might took some days.

**Comment by minhpdn** [comment]
> CDN host for audio is `https://audio.qurancdn.com/` and search is down on staging. Upgrading ES stack, this might took some days.
Thanks for your quick reply, could you please make an inform to me in this ticket when search function is back. 
And I want to ask about the search query
![image](https://user-images.githubusercontent.com/13447967/75302389-36f79c80-5870-11ea-9c1f-527284c97a03.png)

could you please explain more clear about each parameter here, and give some example for me about seach query. 
I'm very appriciate about it.
Thanks,
Minh
