### ISSUE TITLE
Transliteration issue 

### ISSUE THREAD

**Issue by minhpdn** [quran/quran.com-api#237]
Hi guys, 
I met an unexpected  case when I query a verse. 
I'm querying this url 
http://staging.quran.com:3000/api/v3/chapters/1/verses/1
But the translation and transliteration seams weird : 
![image](https://user-images.githubusercontent.com/13447967/75769954-9aeef900-5d79-11ea-8ecf-9596c481aa37.png)

the transliteration text should be "bismi allahi" or something like that but now it's translation text.
Please help me to check.
And another thing, do you have the time when the search engine is back? 
Thanks,
Minh

**Comment by minhpdn** [comment]
@naveed-ahmad please help me by replying this issue , thanks !

**Comment by naveed-ahmad** [comment]
@minhpdn Salam, both issues will be fixed before this Ramadan inshAllah.

**Comment by hasanbasri1993** [comment]
Assalamualaikum 

@naveed-ahmad still in v3
![image](https://user-images.githubusercontent.com/6375150/103484694-72b1aa00-4e23-11eb-8ea9-d756f527cc03.png)

how about in v4 solved ?
But doesn’t work yet 
![image](https://user-images.githubusercontent.com/6375150/103484734-b1dffb00-4e23-11eb-8e7f-c9225ebb2554.png)


Syukran...

**Comment by naveed-ahmad** [comment]
Fixed this in both v3, and v4.
