### ISSUE TITLE
Data is missing with language Chechen

### ISSUE THREAD

**Issue by minhpdn** [quran/quran.com-api#240]
Hi @naveed-ahmad Naveed Ahmad,
I'm getting the language, and there's an omission of verses in Surah 2. There's 77 verses instead of 286.

The data is get by this URL : 
http://staging.quran.com:3000/api/v3/chapters/2/verses?text_type=words&translations=106&offset=75&limit=25
![ảnh](https://user-images.githubusercontent.com/13447967/77278276-7db2a800-6cf1-11ea-906e-f6e3d1c6eaa3.png)

I'm happy to hear your response soon.
Thanks,
Minh

**Comment by naveed-ahmad** [comment]
That 76, 77 is verse number. You're fetching ayahs of the second surah, starting from ayah 75. 

You need to fetch surah info to see total ayah of any surah. 

- Index page for all surah: http://api.quran.com:3000/api/v3/chapters
- Specific Surah: http://api.quran.com:3000/api/v3/chapters/2 

And see `verses_count` attributes for number of ayahs
