### ISSUE TITLE
Slack link doesn't work in README

### ISSUE THREAD

**Issue by superzaky** [quran/quran.com-api#242]
The README consist of this link:
https://quranslack.herokuapp.com

But the link doesn't work for me? See screenshot:
![image](https://user-images.githubusercontent.com/4233200/77702915-dcaa4280-6fb9-11ea-9d41-be2787cb911b.png)

Is there a another slack workspace perhaps? Otherwise the README needs to get updated.

**Comment by mtohmaz** [comment]
Salam,

Were you able to join the slack? Is there a different link?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
post your email and we'll add you.
@naveed-ahmad can we fix this form?
walsalam 3alaikum

**Comment by mtohmaz** [comment]
Email is mahmoud@tohmaz.com, jazaks!

**Comment by ahmedre** [comment]
invited. closing this now.
