### ISSUE TITLE
Need some direction

### ISSUE THREAD

**Issue by imscreed** [quran/quran.com-api#244]
Salaam,

Feeling weird to post this message as an issue. But would love to know if I can use this API for production or do you have another hosted API that can be used for production apps?

I am in the process of building a Startup In-shaa-Allah and need a Quran API to add the Quran feature.  I was going through few APIs and I feel this API is amazing. I also need to provide offline access as well for the verses as well as the audio. The work you guys have done is really amazing. Instead of re-inventing the wheel, I would love to use your API in my apps. 

I will really appreciate if you can please point me in the right direction regarding this. 

Jazakkallah,
Ibrahim

**Comment by naveed-ahmad** [comment]
waAlakim o salam, sorry for the very late response. Please feel free to use our production API, and ill suggest use v4. Released this version yesterday and will keep improving it inshAllah.

**Comment by naveed-ahmad** [comment]
v4 docs are here https://quran.api-docs.io/v4
