### ISSUE TITLE
List Verses endpoint no longer functions 

### ISSUE THREAD

**Issue by GhaziShah** [quran/quran.com-api#245]
Since yesterday, all requests to this endpoint have been responding with `{"status":500,"error":"Internal Server Error"}`. 

You can reproduce this by trying to access data from [any of these URLs](https://github.com/quran/quran.com-api/issues/134#issuecomment-289250204).

**Comment by yassine955** [comment]
I have the same problem akhi. I have a discord bot that gives me a internal error so your'e not the only one. M3a Salama

**Comment by GhaziShah** [comment]
@naveed-ahmad Salaam naveed, I hope you don't mind me tagging you, it's just that parts of our application depend on this

**Comment by naveed-ahmad** [comment]
waAlakim o salam brothers. Sorry, staging api is broken atm and should be fixed tomorrow inshAllah. Staging api was never meant to be used in the production app.

Please switch over to production API.
@GhaziShah @yassine955 

Both formats should work:
- https://quran.com/api/api/v3/chapters/1/verses?page=1&limit=1
- http://api.quran.com:3000/api/v3/chapters/1/verses?page=1&limit=1&offset=1

We've having build tomorrow, that'll also change the api a bit. Added imlaei text, and lots of new translation/fixes.

**Comment by GhaziShah** [comment]
thank you!

**Comment by naveed-ahmad** [comment]
@GhaziShah docs are fixed as well
