### ISSUE TITLE
API Explorer outdated

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [quran/quran.com-api#247]
always get this response result..

![image](https://user-images.githubusercontent.com/9501081/80296841-c528ca00-87b0-11ea-942b-97ace179bdb5.png)

**Comment by mohamedsaeedms** [comment]
yes, it get this resopnse with me too. any solve to it?

**Comment by Amran2k16** [comment]
@naveed-ahmad @mmahalwy Any updates on this?

**Comment by mmahalwy** [comment]
we will fix this. not priority atm as working on new frontend

**Comment by ibrandis** [comment]
You should be able to get the Surahs in json from: https://staging.quran.com/api/surahs

**Comment by mohamedsaeedms** [comment]
any update on it ?

**Comment by mohamedsaeedms** [comment]
any help to solve this problem?

**Comment by Hanzalah-Adalan** [comment]
@mohamedsaeedms alternatively you can use these [APIs](https://alquran.cloud/) from [Islamic Network](https://islamic.network/)

very robust and reliable.. everything CDN..

**Comment by naveed-ahmad** [comment]
@mohamedsaeedms fixed the docs, they recently launched a new product and moved the old app to app.stoplight.io. New app wasn't recognizing my password.
