### ISSUE TITLE
Selected fields in GET request

### ISSUE THREAD

**Issue by muhammadidrees** [quran/quran.com-api#258]
I just went through the docs but couldn't fine any feature of selecting specific fields when using GET request. 

For example if I call to get verses of a surah I get a lot of detailed fields like media, words etc. It would be nice if I can use a filter like '?field=verse' to get only the verses as I don't require that much data.

Thank you.
Great job btw 👏.

**Comment by naveed-ahmad** [comment]
Released the v4 that is a much slim down version of v3. You can specify which fields you need for the most resources. Also released the graphql endpoint, that'll truly solve this issue.
