### ISSUE TITLE
Not able to connect to api endpoint

### ISSUE THREAD

**Issue by romaad** [quran/quran.com-api#260]
Hello, I had a program depending on staging.quran.com:3000/api/v3/.. and it's not working now, the endpoint gives the following error: 

`Failed to connect ... connection refused`

same for api.quran.com
I know I'm missing something here (authentication maybe) but I'm not really sure what's the problem.

thanks

**Comment by tifa2UP** [comment]
Hi @romaad, can you share the exact endpoint that you're trying to call? 

Endpoints in this format work for me: https://quran.com/api/api/v3/chapters/5/verses?page=1&limit=1&offset=1

**Comment by romaad** [comment]
I was using staging.quran.com:3000/api/v3/ and api.quran.com, thanks for the clarification!
