### ISSUE TITLE
Get single verse API only works for Al Fateehah

### ISSUE THREAD

**Issue by ibndias** [quran/quran.com-api#264]
This works: http://api.quran.com:3000/api/v3/chapters/1/verses/2

This one request for Al Baqarah doesn't: http://api.quran.com:3000/api/v3/chapters/2/verses/2

Return: `{"status":404,"error":"Not Found"}`

**Comment by IbrH** [comment]
I'm facing the same problem, and this issue has been posted over 2 weeks ago. Isn't anyone going to look into it?

**Comment by marwan** [comment]
@ibndias @IbrH 

As far as I know this isn’t an issue. The verse numbers are from 1 to 6236. So if the last ayah of Surah 1 is 7, then the first ayah for Surah 2 would be 8. For example:

http://api.quran.com/api/v3/chapters/2/verses/8

Another example of the last ayah of the Quran:

http://api.quran.com/api/v3/chapters/114/verses/6236

Not sure why they made it like that, but it is what it is 🤷🏻‍♂️

**Comment by ibndias** [comment]
@marwan I still don't understand why they make verse sequences like that. Is this written in the documentation?

**Comment by marwan** [comment]
> @marwan I still don't understand why they make verse sequences like that. Is this written in the documentation?

Not sure if it’s written or not. Had to discover it myself.

**Comment by naveed-ahmad** [comment]
Salam brothers, I was working on getting a single ayah. But then realized we don't need this api in quran.com 

Yes, it's kind of broken from the last few years. Working on the next v4 version which has a lot of improvements, will fix single ayah api as well.
