### ISSUE TITLE
Endpoint response is empty

### ISSUE THREAD

**Issue by tahirmq1** [quran/quran.com-api#269]
Assalamoalikum,

I know you guys are updating  but if you can update the endpoint on the docs that will be great

http://api.quran.com:3000/api/v3/chapters/1 gives an empty response

Any positive response is highly appreciated.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
re-enabled api.quran.com for now.
walsalam 3alaikum.

**Comment by tahirmq1** [comment]
Jazakallah khair brother really appreciate it......for the next time if you could inform us beforehand that would be awesome
