### ISSUE TITLE
Fix Get verses by verse_number

### ISSUE THREAD

**Issue by mehdiha** [quran/quran.com-api#274]
Hello,

I have an issue when retrieving a _verse_ by his _verse_number_.
For example, if I want to get the first verse of chapter 2 I call:
http://api.quran.com/api/v3/chapters/2/verses/1
And I have a 404 error.

To have the right verse I have to call : http://api.quran.com/api/v3/chapters/2/verses/8

So I think that it is not returning the verse by the _verse_number_ but by the _id_.

Is it normal? Could you fix that?

Thank you for all this great work!

**Comment by naveed-ahmad** [comment]
Fixed, you can get by ayah number now. Please read the docs again, there are some changes.
