### ISSUE TITLE
Add new recitation

### ISSUE THREAD

**Issue by walidmustafa** [quran/quran.com-api#278]
السلام عليكم ورحمة الله وبركاته

Insha Allah all is well with you. First off, I am an avid user of this app and I thank the team for creating this app as it is simple and beneficial. May Allah accept from you. Jazkallah Khairan... I have a few requests for reciters,
1: Sheikh Kalbani, Youtube: https://www.youtube.com/watch?v=tTVU03bKCzU&t=27s
2: Sheikh Hameed, Youtube: https://www.youtube.com/watch?v=testOR6hH4U&list=LL&index=10
3: Sheikh Okasha, Youtube: https://www.youtube.com/watch?v=YL3_McpoiI8&t=2430s
4: Sheikh Yunus Aswailis, Youtube: https://www.youtube.com/watch?v=BfwSLOHlPrw&t=24s

**Comment by AbirRazzak** [comment]
Can you please request these as 4 separate recitation requests? Thank you.
