### ISSUE TITLE
GraphQL support www.abufathima.com/graphql

### ISSUE THREAD

**Issue by shafeer-tmmt** [quran/quran.com-api#279]
**السلام عليكم ورحمة الله وبركاته**
May **الله**  Reward you, for this Wonderfull effort

Here is the full working GraphQL Api: www.abufathima.com/graphql

Why GraphQL ?
Rest Apis exposed through the project, has lots of information.
If we have the option to select keys, that the developer want from, the exposed key. It would have been nice.

To achieve this we can make use of `GraphQL`
1. With the help of `GraphQL`, we can customise, the response that we get from the server.
2. We can reduce the communication gab between front end and back end, using `GraphQL playground`. 
`GraphQL playground` comes with an _interactive_ auto generated docs

Here is an Example
```
query {
  listChapters(lang: "en") {
    chapters {
      id
      name_simple
    }
  }
}
```

The response will be 
```
{
  "data": {
    "listChapters": {
      "chapters": [
        {
          "id": 1,
          "name_simple": "Al-Fatihah"
        },
        {
          "id": 2,
          "name_simple": "Al-Baqarah"
        },
        {
          "id": 3,
          "name_simple": "Ali 'Imran"
        },
       ...
      ]
    }
  }
}
```
Please note that, here we are not getting all the information, that the chapter has. 
But the information specified in the query.

**الحمد لله**
I have developed the full `GraphQL` api layer for https://quran.api-docs.io/v3
Here is the source: https://github.com/shafeer-tmmt/quran-gql
And here is the full working end point : www.abufathima.com/graphql

**جزاك الله خيرا**

Thank you

**Comment by naveed-ahmad** [comment]
waAlakim o salam, we do have GraphQL endpoint now 

https://api.quran.com/graphql-playground
