### ISSUE TITLE
How to get the chapter with full verse?

### ISSUE THREAD

**Issue by ngekoding** [quran/quran.com-api#291]
Hi, thanks to this great work.

I was read the doc, but can't found how can I get the chapter with full verse (not word by word). 
How can I do that?

Edit:
I use the v4

**Comment by naveed-ahmad** [comment]
You can use [Ayah by chapter](https://quran.api-docs.io/v4/verses/by_chapter) but this route has pagination. You can get max 50 records per API call. Use `words=false` query string if don't need words. 

Second options is [Verse text](https://quran.api-docs.io/v4/quran/get-uthmani-script-of-ayah-2) endpoint. No pagination there, but you can get a single attribute of each ayah. `/v4/quran/verses/uthmani` will return Uthmani text( no words )

**Comment by ngekoding** [comment]
> You can use [Ayah by chapter](https://quran.api-docs.io/v4/verses/by_chapter) but this route has pagination. You can get max 50 records per API call. Use `words=false` query string if don't need words.
> 
> Second options is [Verse text](https://quran.api-docs.io/v4/quran/get-uthmani-script-of-ayah-2) endpoint. No pagination there, but you can get a single attribute of each ayah. `/v4/quran/verses/uthmani` will return Uthmani text( no words )

If I use the second options, can I get the translation also in one API call?

**Comment by ngekoding** [comment]
Trying to use Ayah by chapter, but can't found how to get next page.

<img width="845" alt="No pagination options" src="https://user-images.githubusercontent.com/11625690/107110547-a39e5800-6883-11eb-9407-56ac9b24de0b.png">
