### ISSUE TITLE
How to ignore foot note in translation?

### ISSUE THREAD

**Issue by ngekoding** [quran/quran.com-api#295]
I was used this API a day ago, and now found any changes for the translation with foot_note (Indonesian - id).
How can I ignore this?

Here I attach for example in Al-Fatiha.
<img width="315" alt="Foot Note" src="https://user-images.githubusercontent.com/11625690/107104581-3c6dad00-685d-11eb-8b14-4cfc98949ec5.png">

Thanks

**Comment by ngekoding** [comment]
I use the version v3

**Comment by naveed-ahmad** [comment]
You've got a couple of options: 
- remove footnotes from the text before rendering using a regular expression.  

```
regExp = /<sup\s+foot_note=\d+>\d+<\/sup>/ig
text = "They have no knowledge of it,<sup foot_note=129898>1</sup> nor had their fathers. Grave is the word that comes out of their mouths; they speak not except a lie."

text.replaceAll(regExp, '')
```
- render the translation as HTML, then hide the `sup` tag using CSS

Can't disable footnotes in the api.
