### ISSUE TITLE
Wrong position of word from endpoint get specific verse by key.

### ISSUE THREAD

**Issue by snapshit** [quran/quran.com-api#300]
![Screenshot_20210223-013216](https://user-images.githubusercontent.com/74278819/108753460-599dbd80-7577-11eb-8b81-9a06c11b5b12.png)

Hello brother. If you look the response from https://api.quran.com/api/v4/verses/by_key/1:1?language=en&words=true&translations=134 . You will notice that the verse position is not well ordered by id or by position.

**Comment by naveed-ahmad** [comment]
@snapshit fixed, you can test it here http://staging.quran.com:32782/api/v4/verses/by_key/1:1?language=en&words=true&translations=134
