### ISSUE TITLE
I can't seem to get the search web api to work

### ISSUE THREAD

**Issue by AlGantori** [quran/quran.com-api#309]
I have tried the following

```
http://api.quran.com/api/v3/search?q=water&size=20&page=1&language=en
```
but I get zero response.

I really would like to search for Arabic text (English is extra) and get back JSON of all the verses in Sura/Aaya numbers containing the matched Arabic search string.  Getting back the actual verses in Arabic is not necessary **if it does not contain the found target(s) marked somehow** as I can retrieve it from my assets and perhaps the highlighting/marking.

Thank you.

**Comment by Esmail99** [comment]
@AlGantori  No  fixes yet ?!

**Comment by naveed-ahmad** [comment]
Should be working now, actually deployed the fix beginning of Ramadan.
