### ISSUE TITLE
I found a translation mistake in Surah al-Fatiha

### ISSUE THREAD

**Issue by Lostname777** [quran/quran.com-api#319]
First of all tell me which version " Muhammad Taqi-ud-Din al-Hilali & Muhammad Muhsin Khan" translation are you using as there are many versions with differing things here and there because they don't mention the year in which the version was published.
I have 3 online versions with difference.

**Comment by benomaire** [comment]
i think [this is the source](https://quranenc.com/en/home).

**Comment by Lostname777** [comment]
Ah, I check it that's the issue. Actually the translation and footnotes on that website are altered and have missing things, so that's why quran.com also have translation mistakes. Idk, I want to correct those mistakes but don't know how to explain it, i mean it's not possible to explain it here. Like this the latest version of the translation but still lacks some important things, maybe If one of the developed personally contacts me, it will be possible. And there are changes in Saheeh International translation too, they have updated it and correct some things


[en_Translation_of_the_Meanings_Quran_english_lang.pdf](https://github.com/quran/quran.com-api/files/6307978/en_Translation_of_the_Meanings_Quran_english_lang.pdf)

**Comment by benomaire** [comment]
please explain directly to quranenc. probably this is easier for all of us.

**Comment by polagee321** [comment]
Lostname bro can you tell me what mistake did you find in Muhammad Taqi-ud-Din al-Hilali & Muhammad Muhsin Khan translation of surah fatihah? i am just curious

**Comment by Lostname777** [comment]
I have checked the stuff. The conclusion is that there were many versions of Taqi Ud-Din Hilali's Translation. And many of them had a lot of things in it. But I would request the site owners to keep the site consistent with the latest edition of translation, even if it has removed some things.
https://qurancomplex.gov.sa/kfgqpc-quran-translate-english/
