### ISSUE TITLE
Ruku support

### ISSUE THREAD

**Issue by tahirmq1** [quran/quran.com-api#322]
Assalamoalaikum

Someone asked me to include ruku in the quran and i coudnt find anything related to that in the quran api. Could you please suggest how can i achieve it. 

Also if someone can point me to the arabic font used in quran it would be a big help.

Jazakallah khair. May Allah accept our efforts.

**Comment by tahirmq1** [comment]
Any update on this?

**Comment by thecashewtrader** [comment]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ
I am not part of the quran.com team, but from what I can tell you:

In the frontend    Font

Uthmani    https://github.com/icikiwir/me_quran
IndoPak    https://www.maisfontes.com/pdms-saleem-quranfont
QCF V1 and V2    https://github.com/alquran-foundation/qpc-fonts/

I'm not aware of the Tajweed text fonts
Also, I am not aware on how to implement ruku's 😦.

**Comment by tahirmq1** [comment]
@thecashewtrader  Walekumassalam wrw
I found that there are ruku's in text_indopak but unfortunately the font size is very small and i can't do any to increase it.

Thank you for the arabic fonts I am already using some of them but I will surely check it out.

You can also check my app and share it if you like https://simple-islam.web.app

**Comment by naveed-ahmad** [comment]
https://tanzil.net/res/text/metadata/quran-data.xml

**Comment by naveed-ahmad** [comment]
Ruku support is added, inshAllah this will go live in a few days. Here is the staging API:

Get All rukus:
https://staging.quran.com/api/v4/rukus

Get Single ruku:
https://staging.quran.com/api/v4/rukus/1

Get ayah by ruku
https://staging.quran.com/api/v4/verses/by_ruku/1
