### ISSUE TITLE
repeat is a loop

### ISSUE THREAD

**Issue by IslamSakrak** [quran/quran.com-api#327]
Surahs are going on a loop when I chose 2 repeats it repeats constantly, sometimes it works but usually, it doesn't stop. It seems like it is going on a loop

**Comment by AbirRazzak** [comment]
Hi @IslamSakrak, could you please provide some more details? How are you producing this bug, what is the expected behavior, what is the actual behavior, and please include any additional information such as screenshots or endpoints. Thank you.

**Comment by IslamSakrak** [comment]
it is just a loop 3 is not working 
![image](https://user-images.githubusercontent.com/58050604/116898806-1dea3880-ac37-11eb-917d-208fd137e7ae.png)

**Comment by AbirRazzak** [comment]
This might be a frontend issue, could you please post to https://github.com/quran/quran.com-frontend-v2/issues instead?
