### ISSUE TITLE
Removing a translation does not disable it on mobile

### ISSUE THREAD

**Issue by stalinthegreat** [quran/quran.com-api#330]
Hello, I use quran.com on mobile and since this update there are 2 translations on display. I removed one of them ("Saheeh International") from the Translation list yet this translation is not actually disabled. 
 I tried on a PC and it works fine but this defect happens only on mobile.
![900427fd-05f7-4f2f-87ce-2a2d7507b5ac](https://user-images.githubusercontent.com/59998188/115874502-7570f300-a444-11eb-8336-38bd1455328b.jpeg)
![WhatsApp Image 2021-04-23 at 14 57 19](https://user-images.githubusercontent.com/59998188/115874581-8a4d8680-a444-11eb-9d03-d3d02d298966.jpeg)

**Comment by AbirRazzak** [comment]
Hi @stalinthegreat, this seems to me like a front-end issue rather than an API issue.
