### ISSUE TITLE
translation bug in AYAT UL KURSI

### ISSUE THREAD

**Issue by polagee321** [quran/quran.com-api#338]
Please note that in Surah Bakarah verse 255, if I hover my mouse over the word "كُرْسِیُّهُ", then the translation of the word pops up over "كُرْسِیُّهُ" and it says: "His Throne". However, it should be corrected to just say: "His Kursi" or "His footstool" because the Kursi must not be confused with Al-Arsh (The Throne). 
This is a serious mistake and many authentic translations like 'Saheeh International' and 'Muhammad Taqi-ud-Din al-Hilali & Muhammad Muhsin Khan' have mentioned that do not confuse Kursi with The Throne (Al-Arsh).
The sunnah also indicates that Kursi is different than Al-Arsh (Throne), and this is the consensus of scholars.
For more clarification: https://islamqa.info/en/answers/9566/what-is-the-difference-between-the-arsh-of-the-lord-and-his-kursiy

Please quickly fix this mistake.
![Screenshot (60)](https://user-images.githubusercontent.com/83544715/116819038-b75a1180-ab87-11eb-9c14-8c5273f9b586.png)

**Comment by polagee321** [comment]
i would appreciate it if  the admins could plz send some feedback in, whats the update?
because كُرْسِیُّهُ definitely means Footstool or simply Kursi and it doesn't mean Al-Arsh "The Throne"

Abu Dharr al-Ghifārī said that the Messenger of Allāh (صلى الله عليه وسلم) said:
“The seven heavens in comparison to the Kursī is nothing but like a ring thrown in a desert, **and the excellence of the ʽArsh (Throne of Allāh) over the Kursī is like the excellence of that desert over that ring**.” 
Authenticated as Saheeh by Al-Albani
I would highly appreciate a response, also please don't blindly follow any website even if it says Kursi is "Throne" i.e. Al-Arsh, which is totally wrong interpretation.

**Comment by polagee321** [comment]
sorry are the developers busy? this translation error is still there and no response?

**Comment by naveed-ahmad** [comment]
Salam @polagee321 We're not scholars, so our feedback doesn't matter. Shared your concern with Dr. Mustafa Khatib ( author of Clear Quran translation ) and here is his response:

> It's a long discussion among the scholars and it seems that the person who sent the question is familiar with one opinion only. After reviewing all opinions: Al-'Arsh is the Throne, and the Kursi is the Seat (which is smaller than the Throne. Ibn Abbas says that Al-Kursi can mean (seat of) knowledge. This is why I prefer "Seat" for Kursi. And Allah knows best.

Going to change it to "His Seat" fixed on beta, this will be live soon.

**Comment by polagee321** [comment]
Walaikum Assalam, bro it's still translated to "Throne"

**Comment by polagee321** [comment]
sir i understand that its difficult but please make this addition

**Comment by naveed-ahmad** [comment]
This was fixed on beta last week https://beta.quran.com/2:255 and will goes live with next production build.
