### ISSUE TITLE
Basmala in the beginning of surah At-Tin

### ISSUE THREAD

**Issue by semogamanfaat1** [quran/quran.com-api#341]
Assalamaualaikum,

I found in the surah at Tin, on the first ayat, there is a basmalah.

This is the request:
https://api.quran.com/api/v4/quran/verses/uthmani?chapter_number=95

And this is the response:
![image](https://user-images.githubusercontent.com/42138272/116953360-3dc14100-acb7-11eb-8166-75c7e3575428.png)

Please kindly check this.
May Allah repay your kindness in this world and the hereafter.

Thanks,
Agus

**Comment by naveed-ahmad** [comment]
Fixed, JAK for reporting.
