### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by abbasiar001** [quran/quran.com-api#342]
![Quran-1 Screenshot 2021-05-03 094101](https://user-images.githubusercontent.com/83720687/117176723-3032b680-ad9e-11eb-9800-556303b32d3b.jpg)
![Quran-2 Screenshot 2021-05-03 094003](https://user-images.githubusercontent.com/83720687/117176732-33c63d80-ad9e-11eb-9031-e6bf6a2b6782.jpg)

Every time I start Quran.com it is back on the default translations, how can I change it to default. I really appreciate the user-friendliness of this site and all other related sites. But selecting translation every time is becoming a challenge.

**Comment by abbasiar001** [comment]
I am interested to have one English translation and one in the Urdu language. So every time I go to the Quran.com website it is back with two English Translations

**Comment by AbirRazzak** [comment]
Hi @abbasiar001, this is a front-end issue. Can you please post your feature request in the https://github.com/quran/quran.com-frontend-v2 or https://github.com/quran/quran.com-frontend instead? Thank you.
