### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by MazharulAntor** [quran/quran.com-api#351]
![Screenshot_20210517-021230](https://user-images.githubusercontent.com/43275422/118411257-6f71d900-b6b5-11eb-96be-009b1dae294f.png)

Saheeh International: In 2nd line the word 'alters' should be replaced by 'altars'.

**Comment by naveed-ahmad** [comment]
Fixed and reported to quranenc as well.

**Comment by naveed-ahmad** [comment]
http://beta.quran.com/5:90?font=v1&translations=20
