### ISSUE TITLE
Khalifa Al Tunaiji خليفة الطنيجي

### ISSUE THREAD

**Issue by hamzadeh** [quran/quran.com-api#359]
AsSalam Alaykum wr, requesting to please include the beautiful soothing recitation of Khalifa Al-Tunaji. For Bio and sound clips please see following link. http://www.assabile.com/khalifa-al-tunaiji-73/khalifa-al-tunaiji.htm

Jazak'Allah Khair
Hamid

**Comment by naushervan** [comment]
Wa-ʾalaykumus salāmu wa-raḥmatullāhi wa-barakātuh, brother. For your information, they have Khalifa Al Tunaiji's recitation in their Android application:
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran

If brother @ahmedre can provide the verse timing files for the mobile app to the web team, maybe they can add all of the mobile app reciters to the Quran.com website as well. The mobile app has many more reciters compared to the website. JazākAllāhu khayrā.

**Comment by hamzadeh** [comment]
Thank you brother but I do not have an Android phone which is the problem for non-Android users.
JazakAllah KhairHamid 
    On Friday, May 21, 2021, 11:15:04 AM EDT, Muhammad Naushervan ***@***.***> wrote:  
 
 


Wa-ʾalaykumus salāmu wa-raḥmatullāhi wa-barakātuh, brother. For your information, they have Khalifa Al Tunaiji's recitation in their Android application:
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran

If brother @ahmedre can provide the verse timing files for the mobile app to the web team, maybe they can add all of the mobile app reciters to the Quran.com website as well. The mobile app has many more reciters compared to the website. JazākAllāhu khayrā.

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
@naveed-ahmad - as @naushervan suggested, i have the timing files and can share with you so we can add sheikh Khalifa to the website (though without word by word highlighting today, only ayah by ayah).

@hamzadeh in the meanwhile we also have an [iOS app](https://apps.apple.com/us/app/quran-by-quran-com-%D9%82%D8%B1%D8%A2%D9%86/id1118663303), but in sha' Allah we'll add to quran.com at some point.

**Comment by hamzadeh** [comment]
Alhamdullilah. Thank you to all involved here!

**Comment by hamzadeh** [comment]
Just downloaded on the iOS app. Exactly what I was looking for :) Thanks again.

**Comment by naveed-ahmad** [comment]
We now have Khalifa Al Tunaiji recitation with word-by-word highlighting in the web app. 

checkout next.quran.com
