### ISSUE TITLE
Certain verses in v2 glyph codes are null

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#363]
The first verse of some Surahs is null.
These are all Isolated Letters

Example: Surah Qasas (Number 28)
https://api.quran.com/api/v4/quran/verses/code_v2?chapter_number=28

**Comment by naveed-ahmad** [comment]
Fixed, JAK for letting us know. 
Deployed here for now: https://staging.quran.com:32827/api/v4/quran/verses/code_v2?chapter_number=28

This will go live in few days iA

**Comment by naveed-ahmad** [comment]
Fixed, JAK for letting us know. 
Deployed here for now: https://staging.quran.com:32827/api/v4/quran/verses/code_v2?chapter_number=28

This will go live in few days iA

**Comment by thecashewtrader** [comment]
جزاك اللهُ خير, this is indeed a great api you are maintaining!

**Comment by thecashewtrader** [comment]
Any update on this?

**Comment by naveed-ahmad** [comment]
@thecashewtrader fixed all "null" cases with v1 and v2. Sorry this was simple task, shouldn't have taken that long.

**Comment by thecashewtrader** [comment]
جزاك اللهُ خير
