### ISSUE TITLE
V2 Glyph Code mistake - 6:131 and Page 591

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#365]
The glyph codes for 6:131 are wrong.
https://api.quran.com/api/v4/quran/verses/code_v2?verse_key=6%3A131
Also for page 591 ( 86:1,86:2 and 87:11,87:12 are the same)
https://api.quran.com/api/v4/quran/verses/code_v2?page_number=591

**Comment by naveed-ahmad** [comment]
Glyph codes are correct, it's just in new Madani Mushaf the last ayah is moved to page 592. You can use `fields` query string to fetch page number for new Mushaf. 

https://api.quran.com/api/v4/quran/verses/code_v2?page_number=591&fields=v2_page

See the `v2_page` page field of last ayah, its 592. Weird right?

**Comment by thecashewtrader** [comment]
جزاك اللهُ خير, sorry for the disturbance 😓.
