### ISSUE TITLE
v2_page field is 6:131 and 87:11-12

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#368]
This is a follow up to #365
# 6:131
* the [v2_page field](https://api.quran.com/api/v4/quran/verses/code_v2?verse_key=6:131) for 6:131 should be 145 instead of 144 as it renders correctly with the QCF V2 Page 145 font.
# Page 591 / Surah 87
* The [v2_page fields](https://api.quran.com/api/v4/quran/verses/code_v2?page_number=591&fields=v2_page) for 87:11 and 87:12 should be 592, as they render properly with the QCF V2 Page 145 font.
# Frontend (Using QCF V2 Font)
* [6:131](https://quran.com/6/131) is incorrect on the frontend as well.
* However, [87:11-12](https://quran.com/87/11-12) are both correct on the frontend, even thought the api has a mistake.
* I found this strange, so just wanted to report it.

**Comment by naveed-ahmad** [comment]
JazakAllah kharin for reporting this brother

You were right about 6:131 fixed the v2 page number. https://beta.quran.com/6/131?font=v2

87:11-12 are correct for the web 
https://beta.quran.com/87:12?font=v2

API is using different db, going to update it. Was planning to have build next week but these are important changes. Hopefully we'll have builds both for api and web today.

**Comment by KajuKaVyapari** [comment]
Jazakallah
Also I love the fact that u can ?font= in the beta version
It's so much better

**Comment by thecashewtrader** [comment]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ,
Have there been builds yet?
The page numbers don't seem to be updated on the api.
