### ISSUE TITLE
Regarding use of sounds

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#369]
* Sorry if this is the wrong repo, I am confused whether to post this here or in https://github.com/quran/audio.quran.com/
* I wanted to know if it is ok to use the https://audio.qurancdn.com for personal projects (https://gitlab.com/thecashewtrader/simple-quran - GPL V3 Licensed, and https://gitlab.com/thecashewtrader/simple-recitations - GPL V3).

**Comment by naveed-ahmad** [comment]
Slack is best place for these questions. Feel free to use our CDN.

**Comment by thecashewtrader** [comment]
جزاك اللهُ خير
