### ISSUE TITLE
no arabic script for api get Get list of verses by Chapter

### ISSUE THREAD

**Issue by Nader-mech** [quran/quran.com-api#371]
![image](https://user-images.githubusercontent.com/58700350/121350132-92954e80-c92a-11eb-832f-3d12d2c3baf3.png)

i still get english scripts even i pass a  parameter string (ar) with the request

**Comment by thecashewtrader** [comment]
You could add `&fields=text_uthmani` or `&fields=text_indopak` at the end.
Example:
https://api.quran.com/api/v4/verses/by_chapter/2?words=true&page=1&per_page=10&fields=text_uthmani

**Comment by naveed-ahmad** [comment]
`language=ar` means return word by word translation in Arabic for this api call. Also as br @thecashewtrader suggested, use `&fields=text_uthmani` if you want to fetch Ayah text or `&word_fields=text_uthmani` for word by word text. 

Also read all attributes of all models https://quran.api-docs.io/v4/models then follow the docs. That'll save a lot of debugging time.
