### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by Noor14i** [quran/quran.com-api#384]
Surah Nisa verse 100

The 'Abdul Haleem' translation is missing the first part of the translation

**Comment by naveed-ahmad** [comment]
aSalam o alakim, double checked. 4:100 seems to be correct:

![10043556-d7dbee2577d3655e3009830c71de1608](https://user-images.githubusercontent.com/701567/123872338-64fe5c80-d94e-11eb-99bc-4304a5ae3be4.png)
https://archive.org/details/TheQuranOxfrdWrldClas/page/n103/mode/2up

Beta
https://beta.quran.com/4:100?font=v1&translations=85

Api: https://api.quran.com/api/v4/quran/translations/85?verse_key=4%3A100
>  and if anyone leaves home as a migrant towards God and His Messenger and is then overtaken by death, his reward from God is sure. God is most forgiving and most merciful.

**Comment by Noor14i** [comment]
وعليكم السلام

"Whoever emigrates in the cause of Allah will find many safe havens and
bountiful resources throughout the earth."

*That is missing from the translation. The second half if correct . (The
Abdul Haleem translation. *)

**Comment by naveed-ahmad** [comment]
jazakAllah kharain, you were right. Source PDF had exact same issue, part of 4:100 was with 4:99. Fixed http://beta.quran.com/4/99-100
