### ISSUE TITLE
[Feature Request] Have a "get all ayahs" option

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#397]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ
Firstly جزاك اللهُ خير for the api 💝.

# What
I would love to have an option to fetch all the ayahs as a single json if it doesnt put too much pressure on the servers.

# Why
* It can be helpful to just fetch once and build an app or website around it
* Example: I am making a static website, and I have to go through multiple iterations to get it working right. I do not want to fetch the ayahs every single time. For now, I use a bash for loop to get all the 30 "Juz" objects and then parse them with scripts. But having a proper single endpoint would be extremely helpful

**Comment by naveed-ahmad** [comment]
waAlakim o salam, we already have this https://quran.api-docs.io/v4/quran

You can fetch indopak, Uthmani, QCF glyph codes and any translation in single api call.

**Comment by thecashewtrader** [comment]
Oh I am very sorry, didn't read the docs well enough 😓
