### ISSUE TITLE
[Feature Request] Get whole Qur'an with words

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#398]
# What
* Firstly sorry for creating so many issues 😅.
* This is kinda a follow up to #397, I realised that the issue was something different so making a separate issue.
* I want to be able to fetch the whole Qur'an with words.
## Current `/quran` endpoint
* It does not seem to support `fields` or `word_fields`
![image](https://user-images.githubusercontent.com/81344401/126992789-cb9a47f8-5085-48c6-be74-e3750ed74f50.png)
## Current `/verses` endpoint
* It does not seem to support fetching whole Qur'an at once.
![image](https://user-images.githubusercontent.com/81344401/126993032-c2fb5eb8-e294-43d2-a9cc-8ff11c4a98a0.png)

**Comment by naveed-ahmad** [comment]
Closing this, let me explain:

- 88246 total words, guess we're following KFQC schema, most waqf signs are separate words. Make no sense initialization that many objects in the browser, good luck with the performance. 
- Queries this many rows from DB is also expensive 
- We don't have api for fetching translations for individual words and probably won't add it
- You can also load 50 ayahs with words, can fetch all words using 125 calls ( 6236/50 ). Prepare the your own JSON file and use it if you really need all words.

**Comment by naveed-ahmad** [comment]
> It does not seem to support fields or word_fields
loading 88246 words from db, then rendering will be SLOW. The response will be huge, HUGGGGE.

**Comment by thecashewtrader** [comment]
Understandable  جزاك اللهُ خير

**Comment by thecashewtrader** [comment]
> can fetch all words using 125 calls ( 6236/50 ).
Yea that's what I ended up doing, although I used pages.
I'll drop the [script](https://gitlab.com/thecashewtrader/minimalist-quran/-/blob/main/scripts/raw_verse_data.sh) here incase someone reads this in the future.
