### ISSUE TITLE
Mushaf bug

### ISSUE THREAD

**Issue by rameezraj** [quran/quran.com-api#399]
Error in Surah 9 Ayat 30 in Indopak mushaf . A hamza is missing in yudhaahioona يُضَاهِئُونَ

**Comment by thecashewtrader** [comment]
can confirm, tho it looks like a font issue, not a text one
it renders fine in other fonts
also the hamza *is* there its just not aligned properly
![image](https://user-images.githubusercontent.com/81344401/127744027-bbb87b0d-eb91-4a23-87c3-d7c618bc7a3e.png)

**Comment by naveed-ahmad** [comment]
Yeah, hamza is there and rending fine using me_quran font. It is a font issue. Closing.
