### ISSUE TITLE
Problem with the Indo Pak Text

### ISSUE THREAD

**Issue by ZainabIkram** [quran/quran.com-api#415]
Assalamu Alaikum,
Hope you are doing well.

I have seen on multiple occasions that one of the fatha, kasra (zair, zabar) are missing in the Indo Pak Text. Being a Pakistani Ive often misread that part and later found the error upon listening to the recitation of the word.

This can be a serious issue, and for this reason i wanted to suggest to hide the indo pak font till the problem is fixed.

Hope your team looks into this. By the way I really love your app and pray that it becomes better and better. Ameen. Keep up the good work! Jazak Allah.

**Comment by naveed-ahmad** [comment]
waAlakim o salam br Zain, can you send few sample ayahs?

**Comment by ZainabIkram** [comment]
A few sample ayaat from Surah Araf are as follows:

![Screenshot_20210815-063240](https://user-images.githubusercontent.com/85530113/129464372-b3051955-0fd6-4d51-b1f4-267711191b27.jpg)
Fatha missing in 7:111 as shown above.
____________________________________

![Screenshot_20210815-063400](https://user-images.githubusercontent.com/85530113/129464382-a1663807-8fd7-423a-9eb2-9c9c8de7b39c.jpg)
Kasra/Zair missing in 7:196 as shown above.

____________________________________

![Screenshot_20210815-063540](https://user-images.githubusercontent.com/85530113/129464413-7e40b222-3b0c-4b8c-b46e-376bf44d53c0.jpg)
I am not sure about this but i couldn't read it correctly from here, but I could read this from the "Quran - Naskh" app. The following image is from the "Quran - Naskh" app:
![Screenshot_20210815-063800](https://user-images.githubusercontent.com/85530113/129464491-aeb0cb88-eac4-4ed2-8038-ffa00d58075d.jpg)

____________________________________

![Screenshot_20210815-064425](https://user-images.githubusercontent.com/85530113/129464502-110ca512-2f37-4b33-bc90-7c9b9ff71e03.jpg)
There is a fatha here in 7:104 but it is very hard to see. Just thought I would mention this as well.

**Comment by naveed-ahmad** [comment]
@ZainabIkram jazakAlalh kharain, checkout new indopak script on next.quran.com

This new text and font is very close to printed Mushaf. There are some known incompatibilities and we're working on them.
