### ISSUE TITLE
`hilali` translation at the /quran/translation/18 return empty array

### ISSUE THREAD

**Issue by Kamrulhasan12345** [quran/quran.com-api#424]
Assalamu'alaikum,
Recently, I found that  https://api.quran.com/api/v4/quran/translations/18?verse_key=23%3A34 is returning the following:
![image](https://user-images.githubusercontent.com/32530625/130396417-c486eafa-4c2b-4760-8759-5a6e516c3be0.png)
While with translation_id 19 works perfectly:
![image](https://user-images.githubusercontent.com/32530625/130396484-581cf0a0-05bd-463d-9e85-edbd1c1d40fd.png)
No ayah is returning perfectly in translation id 18 of this route. 
Can you guys check it, what's the issue?

**Comment by naveed-ahmad** [comment]
aAlakim o salam,  we have two Muhsin Khan Hilali translations. The previous version ( id: 18) was disabled/replaced with the newer version. Please use 203 from now on

https://staging.quran.com/api/v4/quran/translations/203?verse_key=23%3A34
