### ISSUE TITLE
" - Missing

### ISSUE THREAD

**Issue by madd-project** [quran/quran.com-api#433]
I don't Know much Grammer, But If you add, " (Quotation) at the end of these lines. it would look right.

![image](https://user-images.githubusercontent.com/64954854/131832889-06f37377-6652-412a-b25d-6d4b02dbdcd8.png)

IDK, It should be, 

˹Consider˺ the Day We will gather them all together then say to those who associated others ˹with Allah in worship˺, “Stay in your places—you and your associate-gods.” We will separate them from each other, and their associate-gods will say, “It was not us that you worshipped!**_"_** (Quotation at last added)

rather than, ˹Consider˺ the Day We will gather them all together then say to those who associated others ˹with Allah in worship˺, “Stay in your places—you and your associate-gods.” We will separate them from each other, and their associate-gods will say, “It was not us that you worshipped!

**Comment by madd-project** [comment]
IDK if I am wrong Correct me..
Thanks, Happy to Help.

**Comment by naveed-ahmad** [comment]
There is no quotation at the end of 10:28 because translation continues and ends at 10:29.

> Allah is sufficient as a Witness between each of us that we were totally unaware of your worship.”

https://quran.com/10:28-29?translations=131
