### ISSUE TITLE
It's not a bug it's a suggestion

### ISSUE THREAD

**Issue by wasee95** [quran/quran.com-api#434]
AoA! May Allah's blessing be upon you guys, You people are doing a great job. 
Kindly add a bit more padding to the right of Urdu translation.
And sometimes the audio stops automatically at the 12th ayah(verse) of any Surah.

Thank You!
JazzakumUllaho khairan.

**Comment by thecashewtrader** [comment]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ
I am not a quran.com contributor, but I think you should post this issue in https://github.com/quran/quran.com-frontend-next, not in this repo.
