### ISSUE TITLE
71:23 word text_indopak misaligned

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#435]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ

The word_field `text_indopak` is misaligned for `71:23`
https://api.quran.com/api/v4/verses/by_key/71:23?language=en&words=true&word_fields=text_indopak

**Comment by naveed-ahmad** [comment]
JAK for reporting, fixed https://staging.quran.com/api/v4/verses/by_key/71:23?language=en&words=true&word_fields=text_indopak

**Comment by thecashewtrader** [comment]
وَ إيَّاكْ
