### ISSUE TITLE
Indopak 91:1 extra whitespace

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-api#438]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ
The indopak text for 91:1 has extra whitespace at the end, which leads to this:
![image](https://user-images.githubusercontent.com/81344401/132340612-1f49f1cb-515f-4b92-a28e-0386d510f50f.png)

**Comment by naveed-ahmad** [comment]
fixed, JAK for reporting.

**Comment by thecashewtrader** [comment]
وَ إيَّاكْ
