### ISSUE TITLE
Unable to get the verse text from the API [beginner]

### ISSUE THREAD

**Issue by wallid** [quran/quran.com-api#458]
Hi,
I've exploreed the documenation of the API specifically the verse model, and I wasn't able to get the version text despite in the scheme example model showing it in the response.

The example model contains the key text_uthmani . However, I am unable to find that in the API when I try it. 

This is probably an easy one - just not really familiar with the API.

**Comment by naveed-ahmad** [comment]
Please join our discord server and ask questions there( also mention the version of API you're using) https://discord.gg/uZZhJDSend github issues are only for reporting bugs.
