### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by doganmeh** [quran/quran.com-api#46]
I assume this quran.com-api is live somewhere. Is there a documentation as to what is available to other developers who could develop using it?

**Comment by mmahalwy** [comment]
We don't. I need to work on that inshallah.

I think this might be a good place to discuss what good documentation would look like. For example, we can use https://github.com/ruby-grape/grape

**Comment by mmahalwy** [comment]
@sharabash ^^

**Comment by doganmeh** [comment]
Do you mean using ruby-grape's documentation as an example?

**Comment by mmahalwy** [comment]
Using the gem to provide documentation.

**Comment by doganmeh** [comment]
From the gem:

> An opinionated framework for creating REST-like APIs in Ruby

If there is already an API, I do not see how will the gem help providing documentation for it.. Sorry if this is a dumb comment.

**Comment by mmahalwy** [comment]
Hmm, you are right! I must have mixed them up. How about this:
https://github.com/Apipie/apipie-rails

**Comment by doganmeh** [comment]
It makes sense now.

**Comment by mmahalwy** [comment]
@doganmeh would love your feedback on https://github.com/quran/quran.com-api/pull/48

**Comment by dashohoxha** [comment]
It seems great to me.

**Comment by mmahalwy** [comment]
Thanks! Inshallah will push to stage soon
