### ISSUE TITLE
Search malfunction

### ISSUE THREAD

**Issue by codedrunk** [quran/quran.com-api#462]
السلام عليكم
The search on quran.com malfunctions when I set the "Language" filter to "English" and go to any page after page 1. The issue is reproducable on all the browsers that I have checked: Chrome, Edge and Firefox.
![quran com search](https://user-images.githubusercontent.com/8420639/138837050-8d07fc82-035f-42b2-932e-22d7ce5279d8.png)

**Comment by naveed-ahmad** [comment]
Please see the search on next.quran.com, lots of these issues are fixed.
