### ISSUE TITLE
get verse by range

### ISSUE THREAD

**Issue by kubido** [quran/quran.com-api#463]
Assalamualaykum,

I found that on the website we can get ayah by range. by putting `{chapterId}/{verseNumberStart}-${verseNumberEnd}` 
for example [https://quran.com/31/12-15?reading=true](https://quran.com/31/12-15?reading=true)

I didn't find how to fetch ayah by range in the API, this could be favorable.

regards

**Comment by naveed-ahmad** [comment]
Try this: https://staging.quran.com/api/qdc/verses/filter?filters=4:5,112:1-2

Sorry, this API isn't documented yet, nor available in v3 or v4. Soon inshAllah, in the meantime feel free to use qdc version.

**Comment by naveed-ahmad** [comment]
Range api is available in v4 now https://staging.quran.com/api/v4/verses/filter?filters=4:5,112:1-2

**Comment by A7med3bdulBaset** [comment]
Thanks @naveed-ahmad Is there a similar one for recitation?
