### ISSUE TITLE
Spelling bug in Chapter 29 verse 42 for Central Kurdish

### ISSUE THREAD

**Issue by SarKurd** [quran/quran.com-api#464]
## Spelling mistake: 
بێگومان خوا خۆی چاكده‌زانێت ئه‌وه‌ی ئه‌و خه‌ڵكه هاناو هاواری بۆ ده‌به‌ن له جیاتی ئه‌و، چه‌نده بێ ده‌سه‌ڵاتن، چونكه 
هه‌ر خۆی __*خواوه‌ن*__ ده‌سه‌ڵاته و زۆریش دانایه ( له‌و بواره‌ی كه بۆ تاقیكردنه‌وه‌ی خه‌ڵكی ڕه‌خساندویه‌تی ).

Word: __*خواوه‌ن*__

## It should be:

بێگومان خوا خۆی چاكده‌زانێت ئه‌وه‌ی ئه‌و خه‌ڵكه هاناو هاواری بۆ ده‌به‌ن له جیاتی ئه‌و، چه‌نده بێ ده‌سه‌ڵاتن، چونكه 
هه‌ر خۆی __*خاوه‌ن*__ ده‌سه‌ڵاته و زۆریش دانایه ( له‌و بواره‌ی كه بۆ تاقیكردنه‌وه‌ی خه‌ڵكی ڕه‌خساندویه‌تی ).

Word: __*خاوه‌ن*__

----
Translation: Burhan Muhammad-Amin
Language: Kurdish
Chapter: 29
Verse: 42

**Comment by benomaire** [comment]
Thank you for the report!
Can you share an image for that page, or the pdf?
جزاكم الله خيرا

**Comment by SarKurd** [comment]
From quran.com or the original translation?

Here both:

![image](https://user-images.githubusercontent.com/13942717/139566516-85f81d41-82d7-43c5-b904-f7ab36c55482.png)

![image](https://user-images.githubusercontent.com/13942717/139566787-286ee7fa-a3d9-431b-9bae-999fdcaf392e.png)

**Comment by naveed-ahmad** [comment]
fixed, jazakAllah kharain for reporting.
