### ISSUE TITLE
Missing tafsir of ayahs

### ISSUE THREAD

**Issue by tauntmachine** [quran/quran.com-api#470]
some ayahs don't have tafsir. how do i resolve it or you haven't added it?
https://quran.com/114:5/tafsirs/en-tafsir-maarif-ul-quran
![Screenshot 2021-11-09 161952](https://user-images.githubusercontent.com/34002347/140915123-d28ff991-4836-4ad8-bd57-c0652aeae42e.png)

**Comment by tauntmachine** [comment]
@naveed-ahmad can u please give me a way or any other API?

**Comment by naveed-ahmad** [comment]
Unlike translation( each ayah has one ), most tafsir authors wrote tafsir for a group of ayah. e.g 1:1 and 1:2 would have the same tafsir.  

This is already fixed, you can fetch tafsir of any ayah. You'll get tafsir text with ayah group. 
https://staging.quran.com/api/qdc/tafsirs/381/by_ayah/1:1?words=true&fields=text_uthmani

I'll port this to v4 API this week inshAllah.

**Comment by tauntmachine** [comment]
@naveed-ahmad  thanks for help. will be waiting for this fix to be pushed to v4. 

JazakAllah Khair.
