### ISSUE TITLE
translations_count in /resources/languages

### ISSUE THREAD

**Issue by habibun** [quran/quran.com-api#485]
![Quran com API](https://user-images.githubusercontent.com/5810350/147317671-f188dbb6-0344-465f-a98e-909a9b752060.png)
https://api.quran.com/api/v4/resources/languages

if a send request to this following API, I am getting a field called **translations_count**

Can anybody explain what is the purpose of this field.

Thanks in advance.

**Comment by naveed-ahmad** [comment]
It tells you how many translations are available for the language.
