### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by asadbaig143m** [quran/quran.com-api#488]
Assalam O Alaikum,

Alhadulillah! Quran.com is a blessing in digital world. Allah give rewards to all related to quran.com. Aamin

There is some missing translation of Surah Baqrah, ayat 255 in Dr Israr Ahmed's translation.

(Not overtakes him slumber nor he sleeps)
(نہ اس کو اونگھ آتی ہے نہ نیند)
(Na us ko oongh aati hai aur na neend)

Recheck the translation and add missing part of ayah.

JazakAllah
Allah Hafiz.
![255](https://user-images.githubusercontent.com/46256622/147783485-4b8f420d-2bec-461f-8574-97031a63f1fc.png)

**Comment by asadbaig143m** [comment]
![translation font](https://user-images.githubusercontent.com/46256622/147784229-913ec427-75f3-4b24-882e-047291b55d92.png)
Assalam O Alaikum,

Alhadulillah! Quran.com is a blessing in digital world. Allah give rewards to all related to quran.com. Aamin

There is no option to change font of translation.
I request you to add this feature and add Jameel  Nastaleeq font, and more famous fonts for user comfort. 

JazakAllah
Allah Hafiz.

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting bhai, fixed.
