### ISSUE TITLE
Is corpus dead?

### ISSUE THREAD

**Issue by doganmeh** [quran/quran.com-api#49]
This may not be the right place for this issue, but I could not find a better one:

I quickly glanced over the commits and did not see any evidence for corpus being part of the API. Seems that is a separate system (in java). 

I also noticed there are bugs in the morphological information downloaded (version 0.4, last updated in 2011?).  Also, there are recent user comments not being responded or worked into the database. 

So, I would like to ask: is the corpus dead? I know it is live on the server, but in terms of development and community? 

If it is, is there any vision in place to revive it, and possibly, make it part of a one coherent API? Who leads it?

Trying to learn @mmahalwy @sharabash @ahmedre .

**Comment by mmahalwy** [comment]
I personally don't know what is happening with corpus but I have embedded the data into our API for usage on Quran.com. It's not live yet but will look like this data structure per word:

```
 "resource_id": 1,
        "ayah_key": "2:1",
        "position": 1,
        "word_id": 30,
        "page_num": 2,
        "line_num": 3,
        "code_dec": 64337,
        "code_hex": "fb51",
        "char_type_id": 1,
        "class_name": "p2",
        "code": "&#xfb51",
        "token_id": 16542,
        "translation": "Alif Laam Meem",
        "transliteration": "alif-lam-meem",
        "corpus": {
          "description": "Verse 1 of chapter 2 begins with the Quranic initials alif lām mīm (ا ل م). These are sequences of letters that occur at the start of certain chapters in the Quran. In Arabic these are known as the disconnected or shortened letters (حروف مقطعة).",
          "image_src": "/wordimage?id=30",
          "segment": {
            "INL": {
              "class_name": "orange",
              "description": "Quranic initials",
              "concept": "",
              "translation": "",
              "prefix": "",
              "grammar": "حروف مقطعة"
            }
          }
       }
```

**Comment by doganmeh** [comment]
Have you come across some lemma in the morphology data version 0.4 downloaded have trailing '2's which is not in buckwalter transliteration? There are about 20 such words..

**Comment by doganmeh** [comment]
I figured it out. Seems they are homonyms (same spelling but different meanings, e.g., EaSaA عصا could mean both 'wand' and 'to rebel'.

**Comment by mmahalwy** [comment]
I am not sure as i am not familiar with the project, I just added the API :(

**Comment by AsimIqbal2nd** [comment]
Kais Dukes, the original author has started working again on V2 of corpus [Quranic Arabic Corpus 2.0](https://qurancorpus.app) and was interested in contacting Quran.com team for discussing future course of action, specially on updating [Quranic Arabic Corpus 1.0](https://corpus.quran.com) to the new version once ready. His Github repo for QAC2 is [Quranic Corpus](https://github.com/kaisdukes/quranic-corpus) .

**Comment by kaisdukes** [comment]
Salam guys, please see an update on corpus 2.0 APIs here -> https://github.com/quran/quran.com-api/issues/628
