### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by fgareeboo** [quran/quran.com-api#493]
When I go to this url:https://www.quran.com/36

I get the following error msg:
![image](https://user-images.githubusercontent.com/2118261/148763919-4ac940fe-7547-473b-b64d-b0e2737b682f.png)

Site works fine for example with this URL for example https://quran.com/18

And once I am on the site, I can go to surah 36 fine.

**Comment by naveed-ahmad** [comment]
This isn't API-related. Closing.
