### ISSUE TITLE
Error 503: Service Unavailable

### ISSUE THREAD

**Issue by abdul-razaq** [quran/quran.com-api#509]
Hello, i am trying to fetch the list of chapters from https://api.quran.com/api/v4/chapters?language=fen and i keep getting an error from the server saying Service unavailable: 503.

**Comment by ahmedre** [comment]
cc @naveed-ahmad - am able to access v3 and qdc but v4 does give a 503 (even if I change language to en here).

**Comment by abdul-razaq** [comment]
@naveed-ahmad Thanks for responding. I just tried v3 as well as v4 and i am getting same 503 error.

Here is the response i got back:

<!DOCTYPE html>
<html>
  <head>
    <title>503 Service Unavailable</title>
  </head>
  <body>
    <h1>Error 503 Service Unavailable</h1>
    <p>Service Unavailable</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 1108452</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by ahmedre** [comment]
please also add the url

**Comment by abdul-razaq** [comment]
@ahmedre Okay. http://api.quran.com/api/v3/chapters

**Comment by ahmedre** [comment]
jazakAllah khair - @naveed-ahmad :

```
F, [2022-02-01T11:01:01.317775 #1] FATAL -- : [b629a91a-7922-4418-ac6c-c0f284d2e5de]   
[b629a91a-7922-4418-ac6c-c0f284d2e5de] ActionView::Template::Error (undefined method `chapters' for #<ChapterPresenter:0x0000564f92ba20d8 @params=#<ActionController::Parameters {"for
mat"=>"json", "controller"=>"api/v3/chapters", "action"=>"index"} permitted: false>, @looka
head=#<RestApi::ParamLookahead:0x0000564f92ba20b0 @params=#<ActionController::Parameters {"
format"=>"json", "controller"=>"api/v3/chapters", "action"=>"index"} permitted: false>>, @l
ocale="en">
```

**Comment by naveed-ahmad** [comment]
@ahmedre fixed, can we have the build?

**Comment by abdul-razaq** [comment]
> @ahmedre fixed, can we have the build?

Still getting same error.

**Comment by ahmedre** [comment]
you tried too early - try again.

**Comment by abdul-razaq** [comment]
> you tried too early - try again.

That's true, i just tried it again and everything seems to be working fine. Thanks guys for swift response.
