### ISSUE TITLE
It does not keep my last listening position.

### ISSUE THREAD

**Issue by zeeshankhan** [quran/quran.com-api#512]
Hi,

Thank you so much for bringing an amazing website.
I use it mostly to listen to the surah but when I load it again it starts from the beginning. 
Is there a way we can keep track of the last listen ayat and start again from there?
This would be great to have.
Thanks a lot.
Jazakum Allahu khairan

**Comment by naveed-ahmad** [comment]
Please post the issue on feedback.quran.com this repository is about the api
