### ISSUE TITLE
How to get Tafsir Ayah by Ayah

### ISSUE THREAD

**Issue by spa5k** [quran/quran.com-api#513]
Can someone give the API url in order to get Tafsir Ayah By Ayah.
I've tried the one in https://quran.api-docs.io/v4/quran/get-a-single-tafsir

by doing 
```
https://api.quran.com/api/v4/quran/tafsirs/169&chapter_number=1
```
but it's not working, it gives empty response - 

```json
{
	"tafsirs": [],
	"meta": {
		"tafsir_name": null,
		"author_name": null,
		"filters": {
			"chapter_number": "1"
		}
	}
}
```

**Comment by iballan** [comment]
Try this:

`https://api.quran.com/api/v4/tafsirs/14/by_ayah/1` // this takes the ayah ID
and
`https://api.quran.com/api/v4/tafsirs/14/by_ayah/114:1` //this take the {chapter}:{ayah_number}

I am not sure why but these links is not in the documentation page! I took them from another issue's answer.

**Comment by DLkhazan** [comment]
Thanks man. Also do share other hidden links. @iballan

**Comment by iballan** [comment]
> Thanks man. Also do share other hidden links. @iballan

You are welcome, As I mentioned in the comment i've got them from another issue under this repo, you can just search and find the one you are looking for 👍

**Comment by spa5k** [comment]
I created a repo for such use case, you can use spa5k/tafsir_api to get ayah by ayah for 27+ tafsirs

**Comment by osamasayed** [comment]
We apologize for the quality of our API docs, we will be improving it over time inshaAllah
