### ISSUE TITLE
Bug: Don't fetching English Tafsir

### ISSUE THREAD

**Issue by mrhrifat** [quran/quran.com-api#515]
Assalamu Alaikum. I am trying to fetch `Tafsir` with English translation of `Tafsir Ibn Kathir` or `Ma Ariful Quran`. But it's not fetching any Tafsir data. Although I'm getting `Arabic or Bengali` Tafsir.
#### Information
- My  Endpoint is
```
verses/by_chapter/${id}?language=en&words=true&tafsirs=169&page=1&per_page=10
```
- Here `169` is a code of Tafsir Ibn Kathir. I have tried both available Tafsir with English Translation. Like `168 & 169`.
- I take Tafsir code from this Url
```
https://api.quran.com/api/v4/resources/tafsirs?language=en
```
#### Review
1. Is there anything missing to my endpoint?
2. Is it a bug of API?
3. If it's a bug please fix it.

**Comment by naveed-ahmad** [comment]
waAlakim o salam, are you on discord? if not here is the invite link https://discord.gg/QKd35PfNSt

Best api for fetching tafisr is:
`https://api.quran.com/api/v4/tafsirs/169/by_ayah/113:2`

Posted some details on this thread 
https://discord.com/channels/852441853386293268/852447678468980756/942402787713626142
