### ISSUE TITLE
Juz 1 missing verse number 141

### ISSUE THREAD

**Issue by Syahrul** [quran/quran.com-api#534]
https://api.quran.com/api/v4/verses/by_juz/1 has a total of 148 records and has 15 pages.
If you count them, the total is only 147 and verse number 141 is missing.

**Comment by naveed-ahmad** [comment]
jazakAllah kharian for reporting, fixed https://staging.quran.com/api/v4/verses/by_juz/1?page=15

We'll have production build in a few days.

**Comment by tahirmq1** [comment]
> jazakAllah kharian for reporting, fixed https://staging.quran.com/api/v4/verses/by_juz/1?page=15
> 
> We'll have production build in a few days.

Any update on this brother?

**Comment by naveed-ahmad** [comment]
this is live bro.

**Comment by Syahrul** [comment]
the live API still not showing the missing verse like in the staging.
https://api.quran.com/api/v4/verses/by_juz/1?page=15
