### ISSUE TITLE
Random Quran Verse endpoint returns the same json each request

### ISSUE THREAD

**Issue by itzmk21** [quran/quran.com-api#537]
https://api.quran.com/api/v4/verses/random?language=en&words=false

Always gives Surah 10, Verse 24

Edit: Now it always gives 6:93

https://api.quran.com/api/v4/verses/random?language=en&words=true
gives a different random surah to when words=false, but after requesting the url it still gives the same surah
also when `language` is different
as well as then no paramaters are gives (`/random`)
they all give different surahs but stay the same surah and never change after each respective request
or doing `/random?<literally any random string here>` gives a random output
like `/random/?2992q2` and `/random/?29947wd`will give different outputs but requesting the same url wont

**Comment by basit3407** [comment]
I am also facing the same issue. to avoid it i am no generating a random number and attaching it in url with each request.

**Comment by naveed-ahmad** [comment]
# First request 

curl -i https://api.quran.com/api/v4/verses/random\?language\=en\&words\=false
HTTP/2 200
server: nginx/1.14.0 (Ubuntu)
date: Fri, 08 Apr 2022 17:41:30 GMT
content-type: application/json; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
access-control-allow-origin: *
vary: Accept-Encoding, Origin
etag: W/"c52f9466a3e94cfd507663fe2ca5bffa"
x-request-id: 829aee55-393c-4715-8070-46051680105b
x-runtime: 0.345037
x-varnish: 345
age: 0
via: 1.1 varnish-v4
accept-ranges: bytes
strict-transport-security: max-age=31536000
```
{"verse":{"id":3448,"verse_number":39,"verse_key":"30:39","juz_number":21,"hizb_number":41,"rub_el_hizb_number":163,"ruku_number":353,"manzil_number":5,"sajdah_number":null,"page_number":408}}
```

# Second
curl -i https://api.quran.com/api/v4/verses/random\?language\=en\&words\=false
HTTP/2 200
server: nginx/1.14.0 (Ubuntu)
date: Fri, 08 Apr 2022 17:41:55 GMT
content-type: application/json; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
access-control-allow-origin: *
vary: Accept-Encoding, Origin
etag: W/"7b0d28f8db7172baa1e89ffeb7efc9ea"
x-request-id: 1fbef718-1800-43c4-b255-156f5e573831
x-runtime: 0.386845
x-varnish: 348
age: 0
via: 1.1 varnish-v4
accept-ranges: bytes
strict-transport-security: max-age=31536000
```
{"verse":{"id":2833,"verse_number":42,"verse_key":"24:42","juz_number":18,"hizb_number":36,"rub_el_hizb_number":142,"ruku_number":306,"manzil_number":4,"sajdah_number":null,"page_number":355}}
```

Results are different, there are no cache headers either. API is working fine IMO, maybe your browser is caching it? 

There are a couple of solutions for this
- Make sure whatever lib you're using for fetching data don't cache the requests 
```
# disable cache for fetch 
fetch(path, {cache: "no-store"})
```
- Or add a query string with random value to bypass the cache 
```
fetch(`${url}&timestamp=random_value`)
```

**Comment by naveed-ahmad** [comment]
btw you can fetch random ayah of a specific surah using `chapter_number` query string 
https://api.quran.com/api/v4/verses/random?language=en&words=false&chapter_number=1

read the docs for more info, you can fetch random ayah of specific surah, juz, manzil, ruku etc

**Comment by itzmk21** [comment]
Yeah I think that is the case.
However it was working perfectly before with no changes to the libraries used both requests and aiohttp (python) and same browser when testing it too before.

**Comment by naveed-ahmad** [comment]
We switched to Cloudflare recently, maybe it is caching.

**Comment by basit3407** [comment]
i set the no cache header in postman and tested it. still i receive the same json response every time. only workaround is to generate random string and attach it in url with every request.
