### ISSUE TITLE
No Tafsirs available in english

### ISSUE THREAD

**Issue by 0911-Mahin** [quran/quran.com-api#542]
I am unable to access english tafsirs:

- "id":169,"name":"Tafsir Ibn Kathir","author_name":"Hafiz Ibn Kathir"
- "id":168,"name":"Maarif-ul-Quran","author_name":"Mufti Muhammad Shafi"

but when try to use them in other endpoints, it says "Tafsir not found".

Not only these specifically but few tafsirs in other languages are also inaccessible.

**Comment by naveed-ahmad** [comment]
Closing, please see https://github.com/quran/quran.com-api/issues/549#issuecomment-1105743514
