### ISSUE TITLE
Juz 3 has Ayyah from Juz 4

### ISSUE THREAD

**Issue by aadimator** [quran/quran.com-api#543]
![image](https://user-images.githubusercontent.com/10383542/161622670-cf557cc4-9e9d-4b9e-9cce-6efca8517b5e.png)
As can be seen in the image (I've also tested in the API), the first Ayyah of Juz 4 is being shown in Juz 3. Juz 4 starts with the next Ayyah, as shown below:
![image](https://user-images.githubusercontent.com/10383542/161622856-b7400e2d-0864-43fc-9056-eb260a3b33b0.png)

**Comment by naveed-ahmad** [comment]
Juz 4 starts from 3:93 so data and API is fine.

**Comment by tauntmachine** [comment]
isn't there only one TYPE of QURAN. As in every other Quranic app juz#4 starts with 3:92.
same case with your juz#11. 
Can your please atleast explain this difference.

reference apps: 
1- Islam 360
2- Quran Majeed (Pak Data)
