### ISSUE TITLE
why mad normal in solaata ٱلصَّلَوٲ changing the font to weird circle 

### ISSUE THREAD

**Issue by umardev500** [quran/quran.com-api#546]
in this **Assolaata** changing to weird circle
![solat](https://user-images.githubusercontent.com/90049965/162611455-e935b0c3-e48a-4485-98fd-c570896debbd.png)

expected like this 
![expect](https://user-images.githubusercontent.com/90049965/162611472-c9d5f3fd-56f1-416c-85c9-00f3f9eb5b62.png)

I'm using uthmani-tajweed from API

**Comment by naveed-ahmad** [comment]
Please use me_quran font for rending this script. I guess you're using KFQC Hafs font and it is not compatible with this script.

**Comment by md-rifatkhan** [comment]
same ٲ is rendering as circle

**Comment by md-rifatkhan** [comment]
@naveed-ahmad mequran font not show end ayah symbol
