### ISSUE TITLE
Tafsirs: tafsir id no: 91, Al Saddi is not working

### ISSUE THREAD

**Issue by Sobhi-Arood** [quran/quran.com-api#550]
Al salam alykum, it seems like tafseer Al Saadi is not available.

url: https://api.quran.com/api/v4/quran/tafsirs/91?chapter_number=1

result: 
{
    "tafsirs": [],
    "meta": {
        "tafsir_name": null,
        "author_name": null,
        "filters": {
            "chapter_number": "1"
        }
    }
}

I tried with different filters like page number and chapter number but nothing seems to work. Other tafseers are working fine.
Please check. Thank you

**Comment by itzmk21** [comment]
A lot of other Tafaseer aren't working either, e.g: Ibn Kathir English (id=169), Tabari (id=15) and more

**Comment by naveed-ahmad** [comment]
waAlakim o salam, we used to have ayah by ayah tafsir but most tafsirs are for a group of ayah so changed the schema and data recently. Old API won't work anymore for some ayahs. 

Please use this new API, it'll give you tafsir text for ayah group(for Ibne Kathir , all ayahs of last surah have one tafsir text. Call API with any ayah you'll get the same group.) 

https://api.quran.com/api/v4/tafsirs/169/by_ayah/114:2
https://api.quran.com/api/v4/tafsirs/169/by_ayah/114:3

**Comment by naveed-ahmad** [comment]
https://api.quran.com/api/v4/tafsirs/91/by_ayah/1:1 is working
