### ISSUE TITLE
How do I get the English translation of a verse?

### ISSUE THREAD

**Issue by acagastya** [quran/quran.com-api#552]
Hi, I am using this API `https://api.quran.com/api/v4/verses/by_key/` to fetch the English translation of the verse.

When I fetch `https://api.quran.com/api/v4/verses/by_key/2:212?&language=en&words=true` and on the result, I do `res.verse.words.map(e => e.translation.text).join(' ')`, I get "Beautified for those who disbelieve[d] (is) the life (of) the world and they ridicule [of] those who believe[d] And those who fear (Allah) (they will be) above them (on the) Day (of) Resurrection And Allah provides whom He wills without measure (212)". 

However when I open https://quran.com/2/212, the translation provided is "The life of this world has been made appealing to the disbelievers, and they mock the believers. Those who are mindful ˹of Allah˺ will rank above them on the Day of Judgment. And Allah provides for whoever He wills without limit."

The above translation is obtained when I hover over the Arabic text.  Which API should I use in order to fetch the translation I mentiond in the thrid paragraph?

**Comment by naveed-ahmad** [comment]
Which translation do you need to fetch? 

Use this API to fetch list of all translations 
https://api.quran.com/api/v4/resources/translations

If you need a translation of one ayah, use the following API( 131 is the id of Clear Quran)
https://api.quran.com/api/v4/translations/131/by_ayah/1:1

**Comment by acagastya** [comment]
Ah, all right, understood.  Thanks, @naveed-ahmad.  The second API is what I needed.  Really appreciate it!

**Comment by acagastya** [comment]
@naveed-ahmad This seems to be missing from the docs.  Is there someone already working on it?  Xor should I send a patch for the docs?

**Comment by naveed-ahmad** [comment]
@acagastya we're going to migrate docs to https://hoppscotch.io/

Clone this repo https://github.com/quran/api-docs and start writing the documentation :)
