### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by acagastya** [quran/quran.com-api#554]
Hi, I was designing a tool which makes use of this API.  It is possible, someone using this tool might end up calling the APIs a lot.  Can you please suggest what would be a fair rate limit I should ensure, so I am not unnecessarily burdening the server?

**Comment by naveed-ahmad** [comment]
Please feel free to use this API and maybe this tool when it's ready. There is no rate-limiting for now, hopefully, servers will handle the load.
