### ISSUE TITLE
Juz ayah difference

### ISSUE THREAD

**Issue by tauntmachine** [quran/quran.com-api#559]
hi, i have been using your API and now i found some differences in juz data from other Quran apps.
Can you please educate me on the following differences.
1- Juz#4 First ayah has been added in juz#3 (ayah no. 3:92)
2- Juz#6 last ayah is missing, has been added in juz#7 (ayah no. 5:82)
3- juz#10 last ayah is missing, has been added in juz#11 (ayah no. 9:93)
4- juz#13 last ayah is missing, has been added in juz#14 (ayah no. 15:1)
5- juz#19 last four ayah are missing, has been added to juz#20 (ayah no. 27:56, 27:57, 27:58, 27:59)
6- juz#21 first ayah is missing, has been added to juz#20 ( ayah no. 29:45)
7- juz#23 first six ayah are missing, has been added to juz#22 (ayah no. 36:22, 36:23, 36:24, 36:25, 36:26, 36:27)

Reference: 
1- Islam 360
2- Quran Majeed (Pak data)

**Comment by tauntmachine** [comment]
can anyone would be kind enough to guide me on this?

**Comment by naveed-ahmad** [comment]
@tauntmachine jazakAllah kharain for reporting brother, API was returning juz numbering from Madani Mushaf. We now have added support for both indopak and madani alhumudaAllah. New api will be available in few days iA. 


Ayah | Indopak Juz | Madani Juz
-- | -- | --
3:92 | 4 | 3
5:82 | 6 | 7
9:93 | 10 | 11
15:1 | 13 | 14
27:56 | 19 | 20
27:57 | 19 | 20
27:58 | 19 | 20
27:59 | 19 | 20
29:45 | 21 | 20
36:24 | 23 | 22
36:22 | 23 | 22
36:23 | 23 | 22
36:25 | 23 | 22
36:26 | 23 | 22
36:27 | 23 | 22

**Comment by naveed-ahmad** [comment]
Deployed on staging, please test and let me know if there is any issue. 

### New api

#### Mushafs
You can fetch list of supported mushafs with different layouts( 15 lines, 16 lines, indopak, madani etc)
https://staging.quran.com/api/v4/mushafs

#### Get juz and verses mapping for indopak
Mushaf with id 6, 7, 14, and 15 are indopak. All other for madani. You can get juz for specific mushaf using `mushaf` query string.

https://staging.quran.com/api/v4/juzs?mushaf=6
https://staging.quran.com/api/v4/juzs/3?mushaf=6


#### Juz for madani mushaf
https://staging.quran.com/api/v4/juzs?mushaf=1
https://staging.quran.com/api/v4/juzs/3?mushaf=1

#### Get ayah by juz for specific mushaf
https://staging.quran.com/api/v4/verses/by_juz/3?mushaf=6
https://staging.quran.com/api/v4/verses/by_juz/3?mushaf=1

`juz_number` attribute of verse object is also depends on value of `mushaf` query string 
https://staging.quran.com/api/v4/verses/by_key/3:92?mushaf=6
https://staging.quran.com/api/v4/verses/by_key/3:92?mushaf=1

Finally, if mushaf query string is not given or has invalid value. API will fallback to default mushaf(id=5 QPC Hafs text)

**Comment by tauntmachine** [comment]
JazakAllah, i have tested on staging, working fine. Some question though.
Will mushaf query string will also be deployed to "verses/by_hizb/" api too? 
Any ETA for the production release? 
Would be really kind of you if you can manage it soon.

**Comment by naveed-ahmad** [comment]
> Will mushaf query string will also be deployed to "verses/by_hizb/" api too?

Yes, and we'll have the production build on 1st August inshAllah.

**Comment by tauntmachine** [comment]
InshAllah
