### ISSUE TITLE
Version 4 

### ISSUE THREAD

**Issue by Mustapha-AJEGHRIR** [quran/quran.com-api#562]
Assalamo Alaykoum, I have seen that you have not released the version 4 yet (github releases) but it is functional. Is it safe to work with it ? (I mean, is it safe to build upon api.quran.com/api/v4/ )

**Comment by naveed-ahmad** [comment]
waAlakim o salam, yes v4 is safe. Feel free to use it. We used to create releases/tags on github but stopped doing that.
