### ISSUE TITLE
Accessible ERD diagram

### ISSUE THREAD

**Issue by osamaramihafez** [quran/quran.com-api#566]
Salam and barakAllahufeekum for all the great work you've been doing mashaAllah.

I recently saw #224 in which @naveed-ahmad mentions that the SQL dump cannot be shared. I was wondering if the full schemas and ERDs could potentially be shared since it's not really proprietary information.

**Comment by naveed-ahmad** [comment]
waAlakim o salam, schema definitions are part of this repo and available here:

https://github.com/quran/quran.com-api/blob/master/db/schema.rb

Not exactly ERD unfortunately, also there are some duplicate tables( like stem and stems. You can ignore the tables with singular name )

Feel free to ping me on discord if we've schema related question.
