### ISSUE TITLE
Add missing waqf sign in v2

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-api#570]
<img src=https://cdn.discordapp.com/attachments/926967226450477057/995759870718525460/unknown.png />

Missing in our fonts

<img src=https://cdn.discordapp.com/attachments/926967226450477057/995759871016308806/unknown.png />

**Comment by naveed-ahmad** [comment]
[p60-v2.zip](https://github.com/quran/quran.com-api/files/9124395/p60-v2.zip)

**Comment by benomaire** [comment]
A kind reminder that v2 fonts match [the print between 1422-1438](https://books.islamway.net/1/ar_Mushaf_AlMadinah_N_G.pdf). Therefore, **the font is correct and no change is needed**, see the image below.
The first image that you showed is for v4 fonts ([available here](https://nashr.qurancomplex.gov.sa/en/)) which match [the print after 1439](https://qurancomplex.gov.sa/en/kfgqpc-quran-hafs-standard/).


![p060](https://user-images.githubusercontent.com/69304392/179348249-5b3f19d3-1b33-4b2a-8c79-8a4d340be905.jpg)

**Comment by naveed-ahmad** [comment]
@benomaire JAK, closing this. 

fyi we're going to add v4 in the next few week inshAllah, fonts file are already splitted into 604 files. Any idea what happens to v3?

**Comment by benomaire** [comment]
Unfortunately, no idea. But it could be a version that matches [Shemerly](https://qurancomplex.gov.sa/kfgqpc-quran-hafs-standardthree/).

BTW, I would have tried to live with the new format without expanding the fonts to 604 fonts again. Benefits are
1. Compatibility with anybody who uses them directly from the Complex, especially if we offer a sharing feature.
2. We're confident that font hashes are exactly the same, so if any weird rendering bug is reported for example, we are sure it is not the font.

I agree that dealing with much less fonts is a bit confusing and a bit heavier on the web, but just wanted to share these thoughts.
