### ISSUE TITLE
Endpoint to check if there's any resources update

### ISSUE THREAD

**Issue by nawaf11** [quran/quran.com-api#575]
Salam Alikom brothers

We need simple endpoint that

return list of all resources that are updated after specific-timestamp

It will help other Projects to have a synced/updated resources (data like word-translation, tranlsations and tafsirs ..)

Many thanks.

**Comment by adropofilm** [comment]
Can't seem to assign this to myself, but I call dibs!

**Comment by naveed-ahmad** [comment]
JAK @adropofilm for implementing this api. It's available at following endpoint and soon will be available on production iA

https://staging.quran.com/api/v4/resources/changes?updated_after=1/1/2022
