### ISSUE TITLE
setup_indicies broken

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-api#62]
100% repro:
- fresh elasticsearch (no data)
- run `RAILS_ENV=production rake elasticsearch:setup_indices`

get an error.
a workaround is to comment out `delete_index` [here](/quran/quran.com-api/blob/develop/app/models/concerns/searchable.rb#L49).

**Comment by naveed-ahmad** [comment]
v2 specific which is removed, that's interesting we can resolve issues by removing code :)
