### ISSUE TITLE
Abridged Explanation of the Quran

### ISSUE THREAD

**Issue by FarisFarley** [quran/quran.com-api#631]
Assalamo Alikum wrb:

First of all i would like to thanks the team who worked hard to make this project. Ma'Sha'Allah wonderful work. May Allah bless all of you and reward for your good intentions Ameen.

Secondly, Iam trying to make a small quran kareem app in Java android. I find the best api for the arabic part (Quran Verses) but the purpose of the app is to display only the **Abridged Explanation of the Quran**. for that purpose iam here. I would really appreciate if the team can provide me JSON data of the (translation=171) i.e Abridged Explanation of the Quran.

JazakAllah khair
Muhammad Faris from Saudiarabia

**Comment by naveed-ahmad** [comment]
https://api.quran.com/api/v4/quran/translations/171?fields=verse_key
