### ISSUE TITLE
[Bug] Surah Al Naml Ayat 62 audio not working

### ISSUE THREAD

**Issue by huzefarana** [quran/quran.com-api#655]
Surah Al Naml Ayat 62 audio not working when I'm signed in but when I log out it works fine.
https://quran.com/en/an-naml/62

**Comment by Abdullah8006** [comment]
Working for me fine on the web!! What platform are you on?

**Comment by huzefarana** [comment]
I'm also on the web(firefox). It's working now never mind.

**Comment by Abdullah8006** [comment]
@ahmedre good to close?
