### ISSUE TITLE
[bug]: API is returning arabic text with extra diacritical marks #2243

### ISSUE THREAD

**Issue by wassim** [quran/quran.com-api#694]
Example word: هُدًۭى → should be → هُدًى

This causes weird display on my frontend:

![CleanShot 2024-11-17 at 22 43 11@2x](https://github.com/user-attachments/assets/f0428674-2149-4bc3-a216-b2c23fc488c8)

Is this a normal behavior?

**Comment by Abdulrahman-Alanazi1** [comment]
Can i ask which language are u using?

**Comment by wassim** [comment]
@Abdulrahman-Alanazi1 `fr` I tried to change to `en` but that doesn't fix it

`https://api.quran.com/api/v4/verses/by_chapter/2?fields=text_uthmani&language=fr&page=1&per_page=20&translation_fields=resource_name&translation_fields=language_id&translations=31&word_fields=text_uthmani%2C%20location&words=true`

**Comment by naveed-ahmad** [comment]
Text us fine this is font issue. Looks like you're using QPC Hafs font, but this test was meant only for me Quran font
