### ISSUE TITLE
invalid ayah gives 500 instead of 404

### ISSUE THREAD

**Issue by ahmedre** [quran/quran.com-api#74]
if we request an invalid ayah, we get a 500. let's instead return a 404? for example, requesting /9/186 results in a 500 error on api

**Comment by atalebagha** [comment]
I'm going to give this a shot, but I don't have much experience in RoR

**Comment by Taym95** [comment]
I want to contribute to this project i need database, how i can get it ?

**Comment by naveed-ahmad** [comment]
there is no such url like /9/186, do you mean /9/verses/186 ? again there were no endpoint in v2 for individual ayah. Closing it. @Taym95 you can email @mmahalwy to get db access.
