### ISSUE TITLE
Require access db part quran api. 

### ISSUE THREAD

**Issue by alivolyty** [quran/quran.com-api#83]
Hi 

Assalamu alaikum,

I have cloned this project. But to run and look the project I need access to DB. As you you mentioned  in doc, can I get access to that repo of db
https://github.com/quran/quran.com-api-db/tree/8dbe996a336dbb57f1a0ff8119e6659d994b3c24
I would like to contribute to the project as well

**Comment by mmahalwy** [comment]
Salam @alivolyty happy to! Can you email me at mmahalwy@gmail.com?

**Comment by alivolyty** [comment]
@mmahalwy Salam. Thanks for replying. I have sent an email
