### ISSUE TITLE
Audio for many reciters is missing

### ISSUE THREAD

**Issue by cpfair** [quran/quran.com-api#85]
Specifically, the following recording selections no longer work - the API returns an empty audio dict, breaking playback. The data appears to be present in the database.

- as-Sudais
- al-Shatri
- ar-Rifai
- al-Minshawi (Mujawwad & Murattal)
- ash-Shuraim

**Comment by naveed-ahmad** [comment]
@mmahalwy @ahmedre something is wrong with dumps! Just loaded dump 17( latest I guess )
 
* Encrypted segments columns still present( I'm sure @ahmedre said he has removed this column )
* Mp3 files for as-Sudais( recitation 3 ), al-Shatri( recitation 4), ar-Rifai( recitation: 5),  al-Minshawi ( [Mujawwad, recitation 9] , [Murattal, recitation 10]), ash-Shuraim( recitation 11) are disabled. Not sure why! 
* Audio file with no url ( recitation 6 ) still in db
* 68596 files with ogg format( I believe we decided to remove ogg and use only mp3 )

**Comment by naveed-ahmad** [comment]
UPDATE loaded dump 18, same issues. ogg are enabled and mp3 are disabled :)

**Comment by ahmedre** [comment]
this comes back to @mmahalwy's commit on quran.com-database, which ignored all commits before it and thus replaced them.

this is the reason we need to switch to incremental updates instead. i'll fix this for now by re-playing the updates by hand on top of Mahallawy's commit and re-deploying.

**Comment by ahmedre** [comment]
deployed, jazakAllah khairan for reporting.

**Comment by mmahalwy** [comment]
@ahmedre is this fixed?

**Comment by ahmedre** [comment]
yes

**Comment by ahmedre** [comment]
yes, was fixed by https://github.com/quran/quran.com-api-db/pull/11 and a deploy.
